### ISSUE TITLE
KMonad crashes when pressing Fn key

### ISSUE THREAD

**Issue by MaxGyver83** [david-janssen/kmonad#104]
I've got a new keyboard that has an "Fn" key. When I press that key while KMonad is running, it crashes:

```
~ ▶ kmonad: toEnum{Keycode}: tag (464) is outside of enumeration's range (0,255)
CallStack (from HasCallStack):
  error, called at src/KMonad/Keyboard/Keycode.hs:312:32 in kmonad-0.4-56W7Nc8ymnhE6sFKf6p2sa:KMonad.Keyboard.Keycode
```

Looks like a bug. I'm just wondering why because I thought that Fn keys are invisible for all operating systems. (This happened on Linux.)

**Comment by eighal** [comment]
See https://github.com/david-janssen/kmonad/issues/72

**Comment by david-janssen** [comment]
I might have a solution, you guys should test it. More info in original issue: #72
