### ISSUE TITLE
How do I load my config file? 

### ISSUE THREAD

**Issue by favetelinguis** [david-janssen/kmonad#109]
Have I missed the documentation on how to actually run this with my custum config?

Im on Ubuntu and have installed Kmonad and made a basic config file. Now what? How do i actually load my config?

**Comment by MaxGyver83** [comment]
You run: `kmonad my_config.kbd` in a terminal.

**Comment by MaxGyver83** [comment]
On Linux, you need to add your user to the `uinput` group. Check this: https://github.com/david-janssen/kmonad/blob/master/doc/faq.md

**Comment by david-janssen** [comment]
Like @MaxGyver said. You can also run `kmonad` from the command line without any arguments to see other command-line options. (At the moment, just the option to check the config for errors without starting, and a flag to adjust the log-level)
