### ISSUE TITLE
Where to add rules.d in Ubuntu 20.04

### ISSUE THREAD

**Issue by favetelinguis** [david-janssen/kmonad#112]
Im getting the error permissions denied when trying to run kmonad. Following the FAQ I try to add my user to the input group which existed on my machine but this does not help. Then Im trying to create the uinput group but when I get to the 3 step in the FAQ and I should add KERNEL=="uinput", MODE="0660", GROUP="uinput", OPTIONS+="static_node=uinput" to /lib/udev/rules.d. On my system rules.d is a folder with 155 files. Which file in rules.d should I add this line to?

**Comment by slotThe** [comment]
On Fri, Oct 02 2020 01:23, Henrik Larsson wrote:
> Then Im trying to create the uinput group but when I get to the 3 step
> in the FAQ and I should add KERNEL=="uinput", MODE="0660",
> GROUP="uinput", OPTIONS+="static_node=uinput" to /lib/udev/rules.d. On
> my system rules.d is a folder with 155 files. Which file in rules.d
> should I add this line to?

This could perhaps be more clear in the FAQ; the "add a udev rule" part
refers to adding a file (i.e. a rule to be read) to that directory.  So,
for example, create `/lib/udev/rules.d/60-kmonad.rules` and put that
line in there.

**Comment by favetelinguis** [comment]
Nice now it works, however when I start my script it start by just create lots of new lines in the terminal until i start typing on the keyboard then it stops inserting new lines. Is the expected?

**Comment by david-janssen** [comment]
Yeah, it's a little bug that needs fixing. The issue is that kmonad starts the moment you press enter, but it only handles releases for buttons that it has pressed itself, so:
- You press 'ret', which goes to the OS
- KMonad starts
- You release 'ret', and KMonad does nothing

Until you tap 'ret' again, the OS doesn't realize that 'ret' has been released.

A simple fix for this is to start kmonad like this: `sleep 1 && kmonad ...`

Also, actual fix in the works.

**Comment by favetelinguis** [comment]
Ok i can live with it for now, not a big thing.
An additional things, it looks like KeyUp and KeyDown is not supported atm, they are not mapped in Keycode.hs. Is it alot of work to add them?

**Comment by slotThe** [comment]
On Fri, Oct 02 2020 06:31, Henrik Larsson wrote:
> An additional things, it looks like KeyUp and KeyDown is not supported
> atm, they are not mapped in Keycode.hs. Is it alot of work to add
> them?

They are supported!  Every key code defined by they `Keycode' type is
available by its lower-case name without the `Key' part at the start
(i.e. `KeyUp' and `KeyDown' becomes `up' and `down' respectively).  The
aliases are simply to either shorten the names or allow for more
mnemonic naming (I especially like KeySleep == zzz :)

**Comment by favetelinguis** [comment]
sweet thanks
