### ISSUE TITLE
Mappings for the "iso" key not working

### ISSUE THREAD

**Issue by stevep99** [david-janssen/kmonad#113]
I have an ISO keyboard with the extra key between the Z and left-shift.  As I understand it, this key should be referred to as "iso" in the configuration file.

Attached is a simple config file which demonstrates the issue. It re-arranges the left-hand bottom-row keys, such that Z is moved to the ISO key and so on. However any mapping that involves the ISO key produces no output. I am using the _**kmonad-0.4.1-linux**_ binary.

Expected result:
iso -> Z
Z -> X
X -> C
C -> V 
V -> B
B -> iso

Actual result:
iso ->  (no output)
Z -> X
X -> C
C -> V 
V -> B
B ->  (no output)

[test_iso.kbd.log](https://github.com/david-janssen/kmonad/files/5318951/test_iso.kbd.log)

**Comment by david-janssen** [comment]
Are you sure that key is called `iso`? I think the key between `shift` and `z` on iso keyboards is called `102d`. The easiest way to check would be to run `evtest` on your input keyboard and see what it tells you about that key-name. Lemme know how it goes.

**Comment by david-janssen** [comment]
Closing an reopening was completely unintentional. Faulty touchpad :)

**Comment by stevep99** [comment]
Yes, can confirm 102d does work!

I was going by the [iso template file](https://github.com/david-janssen/kmonad/blob/master/keymap/template/iso_60.kbd) which calls it "iso". Also the the [Keycode.hs](https://github.com/david-janssen/kmonad/blob/master/src/KMonad/Keyboard/Keycode.hs) file has a reference to "iso" too.

**Comment by david-janssen** [comment]
You are correct! We should fix the template file. It was user-submitted and I could never test it properly since I don't have the hardware. When I fix the documentation I'll close the issue. Thanks for the headsup.

In regards to the `Keycode.hs` file: yes, there is a KeyIso, although I don't know what actually triggers it :-)

**Comment by MaxGyver83** [comment]
I was also wondering which key might be the `iso` key because `102d` works for me. Maybe it depends on the hardware?

**Comment by precondition** [comment]
Oh yeah, you're right, my bad. `KeyIso` is mapped to `<I178>` in Linux which produces absolutely nothing. That keycode has no HID equivalent.
