### ISSUE TITLE
spc when tap lsft when hold and tab when multi-taped strange behavior

### ISSUE THREAD

**Issue by favetelinguis** [david-janssen/kmonad#114]
I have the following where the expected behavior is to get space when you tap, lsft when you hold and tab if you doubble-tap.
  ```lisp
(defalias
  ssh (tap-hold-next-release 145 spc lsft)
  stt (multi-tap 145 @ssh tab))
```
However im getting nothing when tap, lsft when hold and caps-lock when double-tap. Sometimes I get I spc but I dont know why.

  ```lisp
(defalias
  stt (multi-tap 145 spc tab))
  ssh (tap-hold-next-release 145 @stt lsft)
```
Is I change to this tap and doubble-tap work but hold just repeats spc insted of lsft.

Is this the correct way to configure the key im trying to get and how can one explain the behavior I see?

**Comment by favetelinguis** [comment]
Finnaly starting understand.

**Comment by david-janssen** [comment]
Hey there @favetelinguis, sorry for not replying to you sooner, couldn't find the time. I was wondering if you would explain to me what you struggled to understand and how we might improve the documentation to make this clearer to future users? Thanks in advance :-)

**Comment by prabhu-madanagopal** [comment]
@david-janssen @favetelinguis how do you get this working? tap, double-tap and hold button?
