### ISSUE TITLE
Are <> not supported in defsrc

### ISSUE THREAD

**Issue by favetelinguis** [david-janssen/kmonad#116]
Sorry for spaming with questions, its just that I would really like to get this working until monday to replace my current QMK keyboard at work that is broken (and im very close to be "done"). 

I have a Swedish layout keyboard that looks like this:
```
(defsrc
  tab  q    w    e    r    t    y    u    i    o    p    [
  caps a    s    d    f    g    h    j    k    l    ;    '
  lsft <    z    x    c    v    b    n    m    ,    .    /    rsft
            lalt           spc            ralt
)
```
Next to z i have <, however kmonad will not run with this layout, instead I get:
```
kmonad-0.4.1-linux: Parse error at 16:8:
   |
16 |   lsft <    z    x    c    v    b    n    m    ,    .    /    rsft
   |        ^
unexpected '<'
expecting ')' or keycode
```

Im not sure what is casing this error?

**Comment by favetelinguis** [comment]
I saw this was already asked. Closing this

**Comment by humanplayer2** [comment]
I found the place where it was asked, but had found this first.

For others in my situation, [it was asked and answered here.](https://github.com/kmonad/kmonad/issues/323)
