### ISSUE TITLE
Compose key sequences are unreliable

### ISSUE THREAD

**Issue by Gansgar** [david-janssen/kmonad#127]
The input of Umlauten is very unreliable when using the compose key option with the default sequences. I was able to trace the issue back to a too fast execution of the sequence. After building my own with a 5 ms pause in it, it worked reliable and as expected.

```
(defcfg
  ;; For Linux
  input  (device-file "/dev/input/by-path/platform-i8042-serio-0-event-kbd")
  output (uinput-sink "KMonad output" "")
  fallthrough true
)

(defalias ü #(S-RA-P0 " P5 u))
(defsrc          o u)
(deflayer main ö @ü)
```

In this case ö would trigger only every so often and ü would run perfectly.

As I've set the compose key in the settings (Gnome Tweaks), there's no need for me to execute `sleep 1 && setxkbmap ...`.  

My system is an Ubuntu 20.04 LTS with custom 5.7.10 mainline kernel. I'm running on Wayland.

**Comment by slotThe** [comment]
I've experienced absolutely no issues with compose-key sequences so far;
this kind of sluggishness may be a GNOME and/or Wayland issue.

I suppose 5ms should not be perceivable, so adding a little delay to the
key sequence there would probably be okay.

**Comment by Gansgar** [comment]
Yeah. It's probably a Gnome issue.

**Comment by slotThe** [comment]
Can you try if the following patch works for you?

diff --git a/src/KMonad/Keyboard/ComposeSeq.hs b/src/KMonad/Keyboard/ComposeSeq.hs
index 45fe7da..7781b77 100644
--- a/src/KMonad/Keyboard/ComposeSeq.hs
+++ b/src/KMonad/Keyboard/ComposeSeq.hs
@@ -20,6 +20,7 @@ module KMonad.Keyboard.ComposeSeq
 where
 
 import KMonad.Prelude
+import RIO.Text.Partial (replace)
 
 --------------------------------------------------------------------------------
 
@@ -30,7 +31,7 @@ import KMonad.Prelude
 -- 3. A descriptive-name
 --
 ssComposed :: [(Text, Char, Text)]
-ssComposed =
+ssComposed = map (\(t, c, s) -> (replace " " " P5 " t, c, s))
     [ ("' '"      , '´'     , "acute")
     , ( "^ -"     , '¯'     , "macron" )
     , ( "spc ("   , '˘'     , "breve" )

**Comment by Gansgar** [comment]
Worked
