### ISSUE TITLE
Question: alias for KeyMenu

### ISSUE THREAD

**Issue by funollet** [david-janssen/kmonad#132]
I couldn't find an alias for KeyMenu on `src/KMonad/Keyboard/Keycode.hs`. Using `KeyMenu` on the config file doesn't seem to work. What's the proper way to refer to this key?

**Comment by slotThe** [comment]
On Wed, Oct 28 2020 15:21, Jordi Funollet wrote:
> I couldn't find an alias for KeyMenu on
> `src/KMonad/Keyboard/Keycode.hs`. Using `KeyMenu` on the config file
> doesn't seem to work. What's the proper way to refer to this key?
>

You can use `menu`.  More generally, all keys of can be referred to as
their lower case version without the `Key` prefix (e.g. `KeyRecord`
would just become `record`).

**Comment by funollet** [comment]
Thanks!
