### ISSUE TITLE
Very high virtual memory usage

### ISSUE THREAD

**Issue by Gansgar** [david-janssen/kmonad#138]
I've Kmonad running on my laptop, that often hibernates and goes up again. As such I'm able to get quite high up times and I've observed how with time, kmonad is listed in htop with very high virtual memory usage. I'm unsure about the effect on the whole system (I can imagine that this is quite minimal), but I think it is still something to look into.

Here's a screenshot of htop with kmonad using 1TB of virtual memory (red column):
![Screenshot of htop with kmonad using 1TB of virtual memory](https://user-images.githubusercontent.com/14364148/98728873-5b61bd80-239a-11eb-860a-e93febf3b592.png)

**Comment by slotThe** [comment]
This is not KMonad's doing per se, but a GHC thing.  It was introduced
in GHC 8.0.1 [1], more information on the process is available in the
relevant issue on gitlab [2].

On Tue, Nov 10 2020 12:20, Georg Friedrich wrote:
> I'm unsure about the effect on the whole system (I can imagine that
> this is quite minimal)

It actually improves performance ([1] )!  Virtual memory is really just
that---virtual; your OS won't allocate those 1TB anytime soon ;)
Quoting from [1]:

  > Don’t worry though, most of this amount is merely mapped but
  > uncommitted address space which is not backed by physical memory.

[1] https://downloads.haskell.org/~ghc/8.0.1/docs/html/users_guide/8.0.1-notes.html#runtime-system
[2] https://gitlab.haskell.org/ghc/ghc/-/issues/9706

**Comment by Gansgar** [comment]
Okay. Thank you for clarification. Quite an unusual setup by them, but if it works, it works.
