### ISSUE TITLE
Windows 10: Not available under this OS: DeviceSource

### ISSUE THREAD

**Issue by Snaptags** [david-janssen/kmonad#139]
I cannot load any of the demo layouts provided. Most of the time komad doesn't even print debug information and immediately exits with an error:

`Not available under this OS: DeviceSource`

![image](https://user-images.githubusercontent.com/1249745/99446474-3da6d200-291f-11eb-8589-ad09be000e79.png)

Any idea? Am I supposed to install a runtime of any kind? I just downloaded the binary from https://github.com/david-janssen/kmonad/releases/tag/0.4.1

**Comment by MaxGyver83** [comment]
When you use KMonad in Windows, you have to comment out (or delete) the lines regarding Linux and macOS and comment in the lines regarding Windows:

```clojure
(defcfg
  ;; For Linux
  ;; input  (device-file "/dev/input/by-id/usb-04d9_daskeyboard-event-kbd")

  ;; output (uinput-sink "My KMonad output"
    ;; To understand the importance of the following line, see the section on
    ;; Compose-key sequences at the near-bottom of this file.
    ;; "/run/current-system/sw/bin/sleep 1 && /run/current-system/sw/bin/setxkbmap -option compose:ralt")
    ;; "/bin/sleep 1 && /bin/setxkbmap -option compose:ralt")

  ;; For Windows
  input  (low-level-hook)
  output (send-event-sink)

  ;; For MacOS
  ;; input  (iokit-name "my-keyboard-product-string")
  ;; output (kext)
```

**Comment by MaxGyver83** [comment]
Your problem with `neo-test.kbd` looks like a file encoding issue. I think the `kbd` file should be encoded as UTF-8 (without BOM).

**Comment by Snaptags** [comment]
I cloned the repo and am using the files there. The file encoding is fine according to my gVim: 
![image](https://user-images.githubusercontent.com/1249745/99497506-4ecefd80-2976-11eb-957c-3426a5b02b9a.png)

**Comment by Snaptags** [comment]
Thanks for the instructions about editing the config file, it's working now. I did not find a nice place to add a hint about that to the docs. But people looking for the error will at least find this issue 😄

**Comment by slotThe** [comment]
On Tue, Nov 17 2020 23:25, Markus Lasermann wrote:
> Thanks for the instructions about editing the config file, it's
> working now. I did not find a nice place to add a hint about that to
> the docs. But people looking for the error will at least find this
> issue 😄

There is a "Troubleshooting" section in the README, which links to a
FAQ.  Sounds like a great place to put something like this!
