### ISSUE TITLE
The maintainer is unable to maintain

### ISSUE THREAD

**Issue by david-janssen** [david-janssen/kmonad#142]
# Overview

Due to slowly but inexorably worsening health issues the original designer of KMonad (me) is currently unable to put enough time into KMonad to keep up with issues and pull requests. There seems to be the beginnings of a very friendly and capable community building up around the project, and it would be a shame if that community stagnates simply because I was unwilling to relinquish some control. My illness is not terminal, but it certainly is chronic and I am unable to predict if things will improve in 1 week, 1 month, 1 year, or ever. 

# Proposal

I want to relinquish control of KMonad to the community. Of course, since this is an open-source project, that has already 'sort of' been done, because anyone can fork, but then everything becomes a decentralized mess. What I propose is to take on-board 2 or 3 people as administrators of the project, giving them the ability to merge pull requests and tend to issues as they see fit. I will still be available to answer questions and explain how everything is put together, but only sporadically when my health allows.

Additionally, I have registered the kmonad.project@gmail.com (kmonad@gmail.com was already taken) and the kmonad github username. I'd be perfectly content transferring control of this repo to that account and sharing login credentials if that is a better way of organizing things.

# Donations

I've had two people reach out to me over email to offer donations, which to me indicates that there is some sort of impulse to support KMonad financially. What I would like to do is receive future donations into some form of fully transparent bank-account and then offer bounties for bug-fixes. Things always become muddled when money is involved, so I am very open to hearing ideas about how best to implement a system like this.

**Comment by MaxGyver83** [comment]
That's really bad news! I hoped it was something you could recover from quickly and once for all. I wish you to feel better soon!

Of course, I will go on trying to answer beginners' questions. But unfortunately, I can't help with pull requests because I don't understand Haskell code.

**Comment by david-janssen** [comment]
Thanks for the well wishes. It's something strange and auto-immuny. Hopefully something I'll learn to be able to manage, and part of that learning process is going to be energy management. Ergo: looking for contributors :-).

Your help with the beginner's questions is greatly appreciated!

**Comment by slotThe** [comment]
Holy shit.  I wish you all the best David, I really hope this all works
out for you.

I will carefully raise my hand for "knows enough about Haskell to review
merge requests".  As for the account question, I think it would be nice
to have a "kmonad" organization; this way you don't have to move this
repo anywhere else and people can still be added as "team-members" (or
something) with relative ease.  It would also enable us to list
"related" repositories (like editor integration for `.kbd` files) by
just adding it to the org, so users can immediately see if they may be
interested in any of these additional repos.

I have absolutely no experience with donations and how they should be
handled so I will abstain from speculating on that.  On the face of it,
bug bounties sound really fun!  At some point it may be worth setting up
a CI, which some of the money may also be useful for.

**Comment by ibnuda** [comment]
I really wish the best for you, chief.

**Comment by focusaurus** [comment]
Thanks for creating this awesome project and for your courage to share your situation frankly. I've used [bountysource](https://www.bountysource.com/) a few times to add a small financial incentive to certain OSS issues with some success, and I'd be willing to do that for kmonad. I'm open to other approaches too, mostly just wanted to point out that bounty source is something that's up and running and we could easily try out for a bit without any sort of long-term commitment or initial setup required.

**Comment by jchtt** [comment]
So sorry to hear about your health issues :(. I wish you all the best! While my time is pretty tight, I’ll try to keep an eye out and see if I can help with issues. This is a truly awesome project, it really deserves to be kept up. Maybe it'll motivate me to brush up on Haskell again.

**Comment by eighal** [comment]
@david-janssen, I hope you feel much better very soon.

**Comment by eighal** [comment]
I'm tempted to mention kmonad on lobste.rs and on the NixOS discourse or IRC group to see whether any maintainers surface, but I'm not certain that's a good strategy.  Does anyone have advice about this?

**Comment by caplett** [comment]
@david-janssen i wish you the best and hope things will get better soon!
Thank you for all your effort to keep things float.

**Comment by focusaurus** [comment]
@eighal That seems useful to me. I sent messages to some folks directly and a few small online communities I thought might generate some contributor interest. I guess I would say the more likely the group is to be interested and able to contribute (already into keyboard customization, already know Haskell, etc), the better.

**Comment by david-janssen** [comment]
Hey guys,

Just popping in to say thanks for pulling together and trying to figure this out. I've had a few good days and have had a chance to play around a bit with the Advent of Code. I'll try to see if I can get a bit of time in on KMonad soonish. I think it's a really good idea to find some other maintainers, since my health could start turning south again in no time. For now I have invited @slotThe to help out with pull requests and such. I've also looked into setting up an organization, but I think I will still need to migrate the repo to that organization, so I'm not sure if that is the right approach.

Leaving this open to discuss org-issues, possible maintainers, and health-updates/progress.

Thanks again for all the well-wishes :-)

**Comment by slotThe** [comment]
> For now I have invited @slotThe to help out with pull requests and such.

Thank you so much!

> I've also looked into setting up an organization, but I think I will still need to migrate the repo to that organization, so I'm not sure if that is the right approach.

Ah you're right; seems like you can create new projecs under any user of the organisation, but there doesn't seem to be a way to just say "this repos belongs to this org"... I guess in this case it would be best, especially regarding things like the issue(-history), to just leave everything as-is for now.  If someone else knows how to solve this (I will freely admit that I'm not very familiar with how organisations work) then please go ahead!

**Comment by david-janssen** [comment]
> Thank you so much!

Not at all! Thank *you* :-)

I'm going to close this for now, since I have been managing to have a look at kmonad a bit more frequently, and since now @slotThe is around to help keep things rolling. If anyone knows of anyone who is interested in becoming a maintainer/contributor, send them our way and they will be very welcomed.

**Comment by bard** [comment]
> > I've also looked into setting up an organization, but I think I will still need to migrate the repo to that organization, so I'm not sure if that is the right approach.
> 
> Ah you're right; seems like you can create new projecs under any user of the organisation, but there doesn't seem to be a way to just say "this repos belongs to this org"... I guess in this case it would be best, especially regarding things like the issue(-history), to just leave everything as-is for now. If someone else knows how to solve this (I will freely admit that I'm not very familiar with how organisations work) then please go ahead!

@slotThe @david-janssen this might help: https://www.youtube.com/watch?v=sSZHr7Frp3oX

**Comment by schemar** [comment]
> > For now I have invited @slotThe to help out with pull requests and such.
> 
> Thank you so much!
> 
> > I've also looked into setting up an organization, but I think I will still need to migrate the repo to that organization, so I'm not sure if that is the right approach.
> 
> Ah you're right; seems like you can create new projecs under any user of the organisation, but there doesn't seem to be a way to just say "this repos belongs to this org"... I guess in this case it would be best, especially regarding things like the issue(-history), to just leave everything as-is for now. If someone else knows how to solve this (I will freely admit that I'm not very familiar with how organisations work) then please go ahead!

You should be able to *transfer ownership* of this existing repo to the organization. Create a new organization and then check the settings of this repo. If you scroll to the bottom where the „Danger Zone“ is located, you can „transfer ownership“. Links to this repo will be redirected, so old links still work. Check the details when you click „transfer“.

Hope this helps and all the best!

**Comment by dit7ya** [comment]
Sorry to hear this, David. I always feel a very wholesome, friendly, and welcoming vibe from you and how you handle the kmonad project, which is quite rare among FLOSS tbh. I wish a good health and all the best.
