### ISSUE TITLE
Yet another version of tap-hold dependend on the time both keys are pressed together

### ISSUE THREAD

**Issue by Rougemoot** [david-janssen/kmonad#155]
I'm using `tap-hold` a lot to change layers with `c` and `m` just as raise and lower, but with `a` and `;` as well for home row modifiers.

I've elected to use `tap-hold` rather than `tap-hold-next` or `tap-hold-release` because I felt with those the "next" part of those gave me too many false positives.

What I think could be a great alternative (because really, who thinks 4 is enough?) would be looking at how much time the two keys overlap and set in the config how many milliseconds of overlap trigger the "hold" part.

To sum up, with the mini-language found in the tutorial, this is what it would look like:
```
(tap-hold-overlap a 200 100 sft)   ;; first delay is for the hold part, second for the overlap

Ta Tj               --> aj         ;; of course
Pa Tj Ra            --> aj         ;; because neither the hold or the overlap delays were met
Pa 201 Tj Ra        --> J          ;; because the hold delay was over 200ms
Pa Pj 101 Rj Ra     --> J          ;; because even though the hold delay wasn't met, the ovelap delay was
Pa Pj 101 Ra Rj     --> J          ;; even though j was released after a, the overlap delay was met
Pa Pj 99 Ra Rj      --> aj         ;; not this time
Pa 201 Ra           --> sft        ;; of course, the "cancel" behaviour of tap-hold is kept
```

When typing fast you do tend to press successive letters at the same time but not for very long, so I think having these two criteria (hold time and overlap time) being looked out for would result in fewer false positives or false negatives than with the existing alternatives.

What do you think?

**Comment by slotThe** [comment]
I'll look into this (soon, hopefully)—it _sounds_ like something that should be doable in a very similar way that the other `tap-*` buttons are implemented

**Comment by slotThe** [comment]
@Rougemoot I have hacked something together on a [branch of my fork](https://github.com/slotThe/kmonad/tree/tap-hold-overlap).  To me, this feels very _weird_, but it fits the specifications, at least as far as I can tell.  Can you test this to see if it's to your liking?

There's no documentation yet, but you can use the button like this:

``` clojure
  (tap-hold-overlap 200 100 a sft)
```

where the two number are the tap and overlap delay respectively.

**Comment by Rougemoot** [comment]
It does indeed feel pretty weird, especially since I got used to normal `tap-hold-next-release` behaviour. Sorry I wasted your time with this idea, I guess it was worth trying but may not be worth keeping.

**Comment by slotThe** [comment]
Fair enough; I'll close this issue then
