### ISSUE TITLE
Use multiple `iokit-name`s in `defsrc`

### ISSUE THREAD

**Issue by Rougemoot** [david-janssen/kmonad#156]
I'm using kmonad on both my laptop and my desktop, and I like to keep my configs the same via github so when I change something on one machine, I do on the other one too.

I use my internal Macbook keyboard on the macbook (`Apple Internal Keyboard / Trackpad`), and an Apple wireless keyboard on the desktop (`Keymoot`), so they're the exact same, layout-wise.

What I'd like to be able to do is have this in my `defcfg`:

```
(defcfg
				input (iokit-name "KeyMoot|Apple Internal Keyboard / Trackpad")
				...
)
```

Would that be possible in any way?

**Comment by slotThe** [comment]
Kind of, but not really.  This is a very useful feature to have (and if not for the finiteness of time we'd probably already have it ;), but not yet implemented.  There is a tracking issue for it [here](https://github.com/david-janssen/kmonad/issues/90), so I'll close this as a duplicate for now (though feel free to reopen in case I've misunderstood you).

What you _can_ do already (though it's only available in `develop`, meaning you would have to check that out and compile kmonad yourself) is to use command line arguments for the respective `defsrc` entry you want to modify; these always overwrite what's in the config.  For example, suppose you have 

``` clojure
(defcfg
   input (iokit-name "Apple Internal Keyboard / Trackpad"))
```

then you can do 

``` shell
kmonad --input "iokit-name 'KeyMoot'" /path/to/config
```

to overwrite the input specified in the config and set the `iokit-name` to `KeyMoot`.  This and some shell scripting to detect when a keyboard was attached should do what you intended.

**Comment by Rougemoot** [comment]
That'll work perfectly, thank you!
