### ISSUE TITLE
Mod for tmux prefix

### ISSUE THREAD

**Issue by rmrfus** [david-janssen/kmonad#158]
Hi. I found it is extremely useful to use mod instead of prefix in tmux. I.e. ralt-c instead of ctrl-b c, ralt-shift-' instead of ctrl-b shift-' to split screen horizontally.

I successfully implemented this in QMK, but now I'm looking for a way to implement this for non-QMK keyboards and kmonad looks promising. Before I start to invest efforts and time I want to find if it is even possible to do using current abilities of kmonad?
Here is snippet of my qmk keymap.c (layer 1 is just empty layer with all passthrough mappings switched to with RAlt, tmux prefix is set to Ctrl-Space) 

```
    // support of tmux layer. 
    layer = biton32(layer_state);
    if (layer == 1 && !IS_MOD(keycode) && record->event.pressed) {
	    ctrl_down = get_mods() & MOD_BIT(KC_LCTL);
	    shift_down = get_mods() & MOD_BIT(KC_LSHIFT);
	    // we need all this hassle with LSHIFT to trick Kitty not to parse Ctrl+Shift combos.
	    if (shift_down) unregister_code(KC_LSHIFT);
            register_code(KC_LCTL);
            register_code(KC_SPACE);
            unregister_code(KC_SPACE);
	    if (!ctrl_down) unregister_code(KC_LCTL);
	    if (shift_down) register_code(KC_LSHIFT);
            return true;
    }
```

Thanks in advance.

**Comment by recallthis** [comment]
I'm not a pro so I might misunderstand you, but I don't use the standard tmux prefix. Instead I use custom prefix 'table' by binding to a key this command:

    tmux switch-client -T table1

If you used xmonad this would be something like:

   ((modMask, xK_c), spawn "tmux switch-client -T table1") 

Then in my tmux config I just put all my commands under that table:

    bind-key -T table1 : command-prompt  
    bind-key -T table1 n new-window

Not sure if that helps.

**Comment by david-janssen** [comment]
Hey there,

Sorry for the late reply. It is completely possible to bind various keys to other keys in kmonad. I can't really grok your code-snipped, but kmonad can emit a variety of modded keys or sequences of such keys (macros) easily. I've used it myself for inputing certain common emacs sequences because I'd rather configure kmonad than emacs :).
