### ISSUE TITLE
Template for ISO European Keyboard

### ISSUE THREAD

**Issue by Madcliff** [david-janssen/kmonad#161]
Can we get a template that matches the fullsized and TLK european keyboards?

**Comment by slotThe** [comment]
These would look very similar to the already existing US-style variants; you just have to remember the ISO key!

As an example, taking the layout from `keymap/template/us_ansi_tkl.kbd`, adding the ISO key and moving `RET` around a bit: 

```
(defsrc
  esc  f1   f2   f3   f4   f5   f6   f7   f8   f9   f10  f11  f12
  grv  1    2    3    4    5    6    7    8    9    0    -    =    bspc  ins  home pgup
  tab  q    w    e    r    t    y    u    i    o    p    [    ]          del  end  pgdn
  caps a    s    d    f    g    h    j    k    l    ;    '    \    ret
  lsft 102d z    x    c    v    b    n    m    ,    .    /    rsft            up       
  lctl lmet lalt           spc            ralt rmet cmp  rctl            left down rght
)
```

Contributions welcome!

**Comment by slotThe** [comment]
@Madcliff are the templates defined in #173 to your liking?

**Comment by slotThe** [comment]
I'll merge it for now, feel free to reopen if you notice something off
