### ISSUE TITLE
Feature request: `--list-keyboards` option

### ISSUE THREAD

**Issue by MuhammedZakir** [david-janssen/kmonad#165]
`--list-keyboards` --    List all connected keyboards.

macOS code to get a list of keyboards is already done [1]. I understand just this may not be enough to identify the correct keyboard id/name, but it would still be great to have this cli option. 

[1] https://github.com/david-janssen/kmonad/blob/master/c_src/mac/list-keyboards.c

**Comment by slotThe** [comment]
Some thoughts for GNU/Linux: I wonder if the names reported by `/dev/input/by-path` would be enough for this.  it certainly seems suggestive that all keyboard devices end in `kbd`, but I couldn't find any specifications that mandates this with a quick search.  It might be too much of a hack anyways

**Comment by MuhammedZakir** [comment]
I found this [1]. I just tested it and it's working. Note that this captures all devices, rather than just keyboard. 

Actually, I asked this feature when I saw this [2]. I am hoping KMonad will be able to do that someday. :-)

[1] https://github.com/DavRack/skr/blob/master/src/kid/skrkid.c
[2] https://github.com/sezanzeb/key-mapper/blob/main/readme/usage.md#cli

**Comment by slotThe** [comment]
On Sat, Jan 23 2021 08:13, Muhammed Zakir wrote:

> I found this [1]. I just tested it and it's working. Note that this
> captures all devices, rather than just keyboard. 

Yes that exactly queries `/dev/input/by-id'; I'm just not sure how
reliable the naming is. 

> Actually, I asked this feature when I saw this [2]. I am hoping KMonad
> will be able to do that someday. :-)

Kmonad ever supporting anything GUI sounds like a long shot—though of
course not impossible if anyone wants to put in the effort ;)

**Comment by MuhammedZakir** [comment]
I wasn't talking about GUI, but the cli options of Key Mapper [1]. I am satisfied with cli, but of course, GUI is always welcome! :wink: 

[1] Being able to manage sessions, "hot reload" config, use a different config for a keyboard (when it's already being mapped), etc. would be great.

```
key-mapper-control --command autoload
key-mapper-control --command autoload --config-dir "/home/user/.config/key-mapper/"
sudo key-mapper-control --list-devices
key-mapper-control --command stop --device "Razer Razer Naga Trinity"
key-mapper-control --command start --device "Razer Razer Naga Trinity" --preset "~/.config/key-mapper/presets/gamepad/a.json"
```

**Comment by slotThe** [comment]
> I wasn't talking about GUI, but the cli options of Key Mapper [1].

Ah, sorry about that, `eww` must have not redirected my to the `CLI` heading correctly.

> [1] Being able to manage sessions, "hot reload" config, use a different config for a keyboard (when it's already being mapped), etc. would be great.

We already have some CLI options (in the `develop` branch) for all options in `defcfg`; so _some_ of this is still possible.  I'd have to go through that readme more carefully to say what exactly (and hence what is missing), but maybe what we have in `develop` already satisfies you to a degree

**Comment by david-janssen** [comment]
I've given this some thought, but I'm going to close this issue for the following reasons:

1. It adds a lot of OS-specific overhead. I.e. we would need to write this 3 times. The Linux one seems relatively straightforward (but cumbersome) to me, the Mac one I think was already done by @thoelze1, and I think a Windows one might be straight-up impossible, or at least, realllly annoying.

2. It duplicates a feature already completely supported by the OS. It might take a bit of googling, and we could consider adding an entry to the README on how to find your keyboard-names per OS, but once this feature was completely implemented we would have only added a little bit of convenience, but no features.

If 5 years down the line this project is still running and there are no issues, feel free to resubmit this issue and maybe someone will have a go :-). Sorry to disappoint.
