### ISSUE TITLE
menu key doesnt work

### ISSUE THREAD

**Issue by flexagoon** [david-janssen/kmonad#175]
I registered my 'menu' key in the defsrc, however, it doesnt work when kmonad is running.

**Comment by flexagoon** [comment]
So, it looks like 'menu' actually stands for XF86MenuKB key, not just 'Menu'. Is there a way to fix that?

**Comment by slotThe** [comment]
On Tue, Jan 26 2021 09:31, flexagoon wrote:
> I registered my 'menu' key in the defsrc, however, it doesnt work when
> kmonad is running.

How do you know that it doesn't work; what do you expect to happen and
what is the behaviour you are actually getting?

If you want to use `menu' as your compose-key then it may not be the
right key.  Quoting from the tutorial:

  > Please be aware that what `setxkbmap' calls the `menu' key is not
  > actually the `menu' key! If you want to use the often suggested

  >     setxkbmap -option compose:menu

  > you will have to set your compose key within kmonad to `compose' and
  > not `menu'.

**Comment by flexagoon** [comment]
I didnt want to use it as compose, I wanted to remap it to a fuction. However, using 'compose' instead of 'menu' in defsrc helped anyway. Thanks!

**Comment by slotThe** [comment]
On Tue, Jan 26 2021 10:14, flexagoon wrote:
> I didnt want to use it as compose, I wanted to remap it to a
> fuction. However, using 'compose' instead of 'menu' in defsrc helped
> anyway. Thanks!

Your welcome!  If you're in need of a shorter name, you can also use the
alias `cmps'
