### ISSUE TITLE
[Feature Request] key `s` as `shift` only if pressed and hold with one of the keys of the right hand

### ISSUE THREAD

**Issue by abdallahz3** [david-janssen/kmonad#176]
Hi,
I have mapped holding `s` to `shift`, the issue is if I type for example `because` quickly, I get `becauE`, Is there a way to only make holding `s` act as shift if pressed with a subset of the keys(specifically the right hand keys)

Thanks,

**Comment by slotThe** [comment]
On Wed, Jan 27 2021 10:40, abdallahz3 wrote:
> I have mapped holding `s` to `shift`, the issue is if I type for
> example `because` quickly, I get `becauE`, Is there a way to only make
> holding `s` act as shift if pressed with a subset of the
> keys(specifically the right hand keys)

That functionality does not exist, no.  You can, however, try one of the
many tap-style buttons, to see if anything feels more natural to you.
For example, many people who have modifier keys on the home row like to
use `tap-hold-next-release'.

**Comment by abdallahz3** [comment]
I have tried all tap-styles, a couple of times, but all of them unfortunately produce more errors than I would tolerate.
anyway, Thanks for your reply.

**Comment by bard** [comment]
@abdallahz3 that's interesting. I also had high hopes for dual-function keys brought down by the high error rate at fast typing speeds. Do you have direct experience of a system working like you describe, or is it more of an idea?

**Comment by abdallahz3** [comment]
it is more of an idea, it would be great if someone could point us at a system that would allow that.

**Comment by david-janssen** [comment]
> act as shift if pressed with a subset of the keys(specifically the right hand keys)

Just stumbled across this idea, and I like it. I'm already brainstorming a change to the core of how we represent buttons that might make something like this possible. Don't expect this anytime sooooon, but it's in the mental queue.

**Comment by abdallahz3** [comment]
glad to hear that you like the idea, after I opened this issue, I found an open source project in rust that does mapping(as I'm more familiar with rust than haskell), and I mapped `s` to shift and `l` to shift also, but if I press `s` and then `l`(which is supposed to type `L`) not always works as both keys when pressed act as `shift`, and that was unusable, so what I did is I changed the code(rust project) to make pressing `s` and `d` to act as shift, that way if I pressed `l` while `s` and `d` are pressed, we can know for sure that `s` and `d` are shift and `l` is just a key press, and I did the same to the right hand, I mapped `l` and `k` to act as shift if pressed together.
now after I managed to do that(mapping two keys to act as `shift`), I noticed that if I want to write for example the capital letter `M`, I have to press `s`, `d` and `m`, and I usually press them all at once, and I noticed that sometimes I press `m` just slightly before `d`, and that does not register a `shift`, so what I did is I altered the code to look at the current three presses if there is any, and search for a shift in the three presses, if one is found, register a shift with the remaining key, and that worked and I was kind of happy with it, except for some weird reason pressing `l`, `k` and `r` does not work also with the key `5`, just these two keys, I searched online and it seems to be related to n-rollover, and after that I gave up.

sorry for the long response, but I thought I share the steps I went through as that might be of help.

**Comment by david-janssen** [comment]
> sorry for the long response, but I thought I share the steps I went through as that might be of help.

No need to apologize, these sharings-of-thought-process are very helpful in understanding what you are trying to do. Currently working on other issues, but when I make some progress on this I'll update this issue.
