### ISSUE TITLE
Linux: BT keyboard appears at new path on every connection

### ISSUE THREAD

**Issue by wmertens** [david-janssen/kmonad#178]
I'm looking into using this, it looks amazing, but I don't know how to connect to my Bluetooth Low Energy keyboard. It appears at a new node every time it reconnects and there's no symlink made:

```
Jan 29 12:41:58 wmertens-nixos kernel: input: TextBlade 2-44 Keyboard as /devices/virtual/misc/uhid/0005:000D:0000.0023/input/input86
Jan 29 12:41:58 wmertens-nixos kernel: input: TextBlade 2-44 Consumer Control as /devices/virtual/misc/uhid/0005:000D:0000.0023/input/input87
Jan 29 12:41:58 wmertens-nixos kernel: hid-generic 0005:000D:0000.0023: input,hidraw2: BLUETOOTH HID v1.10 Keyboard [TextBlade 2-44] on 0c:7a:15:86:ba:31
Jan 29 13:40:19 wmertens-nixos kernel: input: TextBlade 2-44 Keyboard as /devices/virtual/misc/uhid/0005:000D:0000.0024/input/input88
Jan 29 13:40:19 wmertens-nixos kernel: input: TextBlade 2-44 Consumer Control as /devices/virtual/misc/uhid/0005:000D:0000.0024/input/input89
Jan 29 13:40:19 wmertens-nixos kernel: hid-generic 0005:000D:0000.0024: input,hidraw2: BLUETOOTH HID v1.10 Keyboard [TextBlade 2-44] on 0c:7a:15:86:ba:31
Jan 29 15:23:37 wmertens-nixos kernel: input: TextBlade 2-44 Keyboard as /devices/virtual/misc/uhid/0005:000D:0000.0025/input/input90
Jan 29 15:23:37 wmertens-nixos kernel: input: TextBlade 2-44 Consumer Control as /devices/virtual/misc/uhid/0005:000D:0000.0025/input/input91
Jan 29 15:23:37 wmertens-nixos kernel: hid-generic 0005:000D:0000.0025: input,hidraw2: BLUETOOTH HID v1.10 Keyboard [TextBlade 2-44] on 0c:7a:15:86:ba:31
```

That last connection resulted in event16 and event17 being mapped in /dev/input.

is this something that needs to be configured in udev?

**Comment by slotThe** [comment]
Using `/dev/input/by-path` is kind of brittle for this reason; it's almost a miracle that it works as well as it does most of the time.  There is `/dev/input/by-id`, which should not change when you plug/unplug your keyboard, so if that directory exists then try to use that instead. 

But pretty much this is something that has to be configured outside of kmonad, yes; as such I'll close this issue for now

**Comment by wmertens** [comment]
There's no symlink in by-id :(

I wonder if kmonad should not have some support for enumerating devices?

For example, Karabiner could be configured to disable the internal keyboard if an external one was connected

**Comment by MaxGyver83** [comment]
I have the same problem. My workaround is using [this (fish) script](https://github.com/MaxGyver83/dotfiles/blob/master/scripts/bin/start-kmonad-for-all-keyboards.fish) for starting KMonad.

Basically, I find my keyboard using this command:

```sh
set keyb /dev/input/(grep -B 8 -A 4 12001 /proc/bus/input/devices | grep RK-Bluetooth -A 4 | grep -oE 'event[0-9]+')
```

In bash syntax:

```sh
keyb=/dev/input/$(grep -B 8 -A 4 12001 /proc/bus/input/devices | grep RK-Bluetooth -A 4 | grep -oE 'event[0-9]+')
```

Of course, you would have to replace "RK-Bluetooth" with something else.

**Comment by slotThe** [comment]
Yes much of this is doable via small scripts, the `develop` branch also features an experimental CLI that makes this a little easier

#90 tracks all of these "I wish I could change the config in a smarter way without scripts" things
