### ISSUE TITLE
KMonad is now packaged for GNU Guix

### ISSUE THREAD

**Issue by ajgrf** [david-janssen/kmonad#18]
I just thought you'd like to know that KMonad is now packaged for [GNU Guix](https://guix.gnu.org/). For now it is stuck on version 0.2, but it will be updated soon when Guix moves to a newer Stackage LTS (kmonad has depended on GHC 8.6 since commit 83049b9, in case you didn't realize).

Users of the Guix package manager can install it by running `guix install kmonad`, and copying the udev rules into place with `sudo cp $(guix build kmonad)/lib/udev/rules.d/70-kmonad.rules /lib/udev/rules.d/`.

Users who run Guix System to manage their entire machine will instead want to install the udev rules by putting something like this into their system's `config.scm`:

    (use-modules (gnu packages haskell-apps))
    
    (operating-system
     ;; ...
     (services
      (modify-services %desktop-services
        (udev-service-type config =>
          (udev-configuration (inherit config)
           (rules (cons kmonad
                        (udev-configuration-rules config))))))))

**Comment by david-janssen** [comment]
Wow, I'm so happy to hear that someone has gone through the effort of packaging kmonad up for distribution! I'll include the installation information in the README when I return from holidays in November, after which I will close this issue.

(Also: I didn't realize I depended on 8.6. Thanks for the headsup. I'll include this in the installation instructions as well.)

Cheers!

**Comment by slotThe** [comment]
> I just thought you'd like to know that KMonad is now packaged for [GNU Guix](https://guix.gnu.org/). For now it is stuck on version 0.2, but it will be updated soon when Guix moves to a newer Stackage LTS (kmonad has depended on GHC 8.6 since commit [83049b9](https://github.com/david-janssen/kmonad/commit/83049b9705251a1c0b182009a0aab24480ef2b86), in case you didn't realize).

Woops, looks like this seems to be my fault.  From quickly glancing over the commit the only thing that seems new-ish if the `nubOrd` function being in containers (please correct me if this is wrong, sadly I'm unable to test this right now), so maybe we should just put it in the file directly to get rid of that dependency on 8.6

**Comment by david-janssen** [comment]
The dependency on 8.6 should be gone now in in 2e16479c78c959955c010b8e6b49e918c6d35519, I simply copied over the code from `containers` for now. This is something we should undo again in the future, but should make packaging easier.

**Comment by david-janssen** [comment]
I've added info about Guix to the README and am closing this issue.

**Comment by ajgrf** [comment]
Thanks for mentioning Guix in the README! I just updated the package to kmonad 0.3.0. Guix moved to Stackage LTS 14 yesterday, so I didn't end up needing the changes in 2e16479.

**Comment by david-janssen** [comment]
Great to hear, because I just started writing code that uses the existential constraints extension introduced in ghc8.6, so soon we will depend on it again ;-)
