### ISSUE TITLE
Shift getting locked down while running and failing to parse '{}' and persisting after taskkill

### ISSUE THREAD

**Issue by mononen** [david-janssen/kmonad#195]
This is an issue specific to the keycode-refactor branch, I'm running into the error:
```
Encountered error in KeySink: Lookup failed during parsing: }
CallStack (from HasCallStack):
  error, called at src\\System\\Keyboard\\Types.hs:109:14 in kmonad-0.4.1-Gn7mvMyxOciAoHmNBEmQOf:System.Keyboard.Types
Encountered error in <emitter_proc>: Lookup failed during parsing: }
CallStack (from HasCallStack):
  error, called at src\\System\\Keyboard\\Types.hs:109:14 in kmonad-0.4.1-Gn7mvMyxOciAoHmNBEmQOf:System.Keyboard.Types
```
Kmonad then stays running, but doesn't interact on any new keyevents (keyboard goes back to behaving like normal), however all  keypresses are as if shift were being held down. Upon killing kmonad, the keypresses will continue behaving as if shift were held down. The way I've found to recover from the shift issue is by spamming the button a few times.

I'm on Windows 2004, Build 19041.804, and have tried the last 6 commits on the branch.
This error does not occur on master.

**Comment by mononen** [comment]
Actually, I managed to fix the issue by setting fallthrough to false.
Feel free to reopen if I'm needed to gather more information as to why the error was occurring.

**Comment by mononen** [comment]
Actually part 2, setting fallthrough to false does not fix the issue, and my 'fix' of spamming shift a few times doesn't actually work until you kill kmonad. As far as I can tell, there is no way to get it from releasing the shift key.

**Comment by david-janssen** [comment]
> keycode-refactor 

You got `keycode-refactor` running on your system? Much impressed, that was purely a tinkering branch that I put online as a in-case-of-fire backup. The branch has since then been deleted, but I have a pile of notes that I will be incoorporting into master in the upcoming weeks, so I'm closing the issue.
