### ISSUE TITLE
No obvious error in debug log, but kmonad appear to do nothing... am I missing something?

### ISSUE THREAD

**Issue by antoniotrkdz** [david-janssen/kmonad#196]
Almost certainly yes.
I followed the instructions in the FAQ.
I am using linux binary from the releases section.
I determined the by-id name of my keyboard.
I am starting kmonad from x terminal using the -l debug flag.
I get no obvious error:
```
$ kmonad/kmonad-0.4.1-linux kmonad/tutorial.kbd -l debug
Opening KeySink
Registering Uinput device
Running UinputSink command: "/bin/sleep 1 && /usr/bin/setxkbmap -option compose:ralt"
Opening KeySource
Initiating ioctl grab
Launching process: emitter_proc
```
Nothing happens.... keys are unchanged and I can't get into any layer...
What am I doing wrong?

**Comment by slotThe** [comment]
On Mon, Mar 08 2021 03:03, antoniotrkdz wrote:
> ```
> $ kmonad/kmonad-0.4.1-linux kmonad/tutorial.kbd -l debug
> Opening KeySink
> Registering Uinput device
> Running UinputSink command: "/bin/sleep 1 && /usr/bin/setxkbmap -option compose:ralt"
> Opening KeySource
> Initiating ioctl grab
> Launching process: emitter_proc
> ```
> Nothing happens.... keys are unchanged and I can't get into any layer...
> What am I doing wrong?

I'm going to assume you are grabbing the right keyboard (though it never
hurts to double check that).  We don't have a file called
`kmonad/tutorial.kbd' (unless you've moved the tutorial from `keymap' to
that directory); is that your personal configuration?  If yes, would you
mind posting it?

What do you see any log output when pressing different keys?  If started
with `-ldebug`, kmonad should produce something like 

    --------------------------------------------------------------------------------
    Received event: Press <j>
    Running hooks
    Registering untimed hook: 1
    Emitting: Press <n>
    --------------------------------------------------------------------------------
    Received event: Release <j>
    Running hooks
    Emitting: Release <n>
