### ISSUE TITLE
Run kmonad in check mode

### ISSUE THREAD

**Issue by mwgkgk** [david-janssen/kmonad#20]
Proposal: a flag to only check the file argument, without launching.

Why: I've tried to use [vim-quickrun](https://github.com/thinca/vim-quickrun) with kmonad as a poor man's lint / makeprg, but kmonad never exits.

**Comment by mwgkgk** [comment]
Somewhat related: here's simple Vim support for kmonad files:

https://github.com/mwgkgk/kmonad-vim

**Comment by david-janssen** [comment]
Hey there. That's a really good idea! I'll make sure to implement it when I improve the CLI, and close this issue when I've added your idea. Thanks :-)

**Comment by david-janssen** [comment]
Should've closed this a while ago. Support for this now exists in 'refactor' with the '-d' flag.
