### ISSUE TITLE
tap-hold-next-release-or-repeat

### ISSUE THREAD

**Issue by franco** [david-janssen/kmonad#200]
Beginner question: I would like to use [home row mods](https://precondition.github.io/home-row-mods) and according to  the [config tutorial](https://github.com/david-janssen/kmonad/blob/master/keymap/tutorial.kbd) `tap-hold-next-release` would be my friend, right? That works okay but I would like the pressed key to repeat after a while if no other key is pressed next. E.g. I use `j` as shift modifier. 
```
  definition for j key:  (tap-hold-next-release 200 j rsft)

  Tj              -> j
  Pj 100 e   -> E
  Pj 300     -> jjjj (and repeating)
```
Can I achieve this behaviour already with existing functions or would that require a new function similar to `tap-hold-next-release` which would allow for a timeout or something?

**Comment by MaxGyver83** [comment]
@slotThe has started implementing something similar: When you press `j` twice quickly, it will be repeated (on his branch). But this causes another bug. Check this issue: https://github.com/david-janssen/kmonad/issues/163 (_Implement QMK's TAPPING_FORCE_HOLD (and a way to disable it)_)

**Comment by franco** [comment]
Thanks @MaxGyver83. #162 is what I was looking for.
