### ISSUE TITLE
Check if config file was changed before running it.

### ISSUE THREAD

**Issue by kurisu170** [david-janssen/kmonad#201]
Currently kmonad just runs the config file whether it changed or not, so anyone can just insert  `rm -rf /*` into it and you would not notice it.

It probably should be made so if config file was changed user should explicitly allow it using for example
`kmonad --allow config.kbd` or `kmonad -a config.kbd`.
If file has not been changed user should be able to run it using just `kmonad config.kbd`.

One way i saw this check performed is in [direnv](https://github.com/direnv/direnv), which calculates hash of config file, stores config file path in `~/.local/share/direnv/<calculated hash>` and if hash and path does not match or don't exist user must explicitly allow file to be read using `direnv allow`.

**Comment by slotThe** [comment]
On Mon, Mar 15 2021 15:13, kurisu170 wrote:
> One way i saw this check performed is in
> [direnv](https://github.com/direnv/direnv), which calculates checksum
> of config file, stores config file path in
> `~/.local/share/direnv/<calculated hash>` and if hash and path does
> not match or don't exist user must explicitly allow file to be read
> using `direnv allow`.

I fail to see how this would provide any additional security.  If an
attacker has access to your `.kbd` file and can insert an `rm -fr ~/*`
there, surely they can also easily recalculate the hash and store it in
the right place?

**Comment by kurisu170** [comment]
Then what about making `allow-cmd` command line option and removing it from config file altogether?
This way i can at least know that any config file i run without this argument would not run some random scripts (assumming of course that startup script is read-only and someone did not tamper with my aliases).

**Comment by slotThe** [comment]
I think it would still be convenient to have it in the config file.  However, I just had a though: the `develop` branch has command line options and those _always_ override what's given in the config file.  So if you disable `allow-cmd` from the comman line when starting kmonad it'll definitely be off.  Is that about what you wanted?

**Comment by kurisu170** [comment]
So something like `kmonad --allow-cmd=false config.kbd` will disable commands whether it is allowed in config or not, right? If so then yes, this is what i wanted. You can close the issue now.

**Comment by slotThe** [comment]
Yup exactly!  I will close this then
