### ISSUE TITLE
Support for sticky modifier keys

### ISSUE THREAD

**Issue by stevep99** [david-janssen/kmonad#202]
I'm trying to figure out if this is supported or not. I've looked at the existing options, but none seem quite right as far as I can tell. What I'm after is being able to implement sticky modifiers, with a timeout, which would obey the following rules:

1. Tapping a key activates a modifier and keeps it active for a predefined timeout period.
2. Tapping another key during the timeout period causes the modifier to be applied to that key.
3. The modifier is deactivated after the first output (i.e. tapping two keys within the timeout period means the modifier only applies only to the first).
4. Tapping a key after the timeout is equivalent to not having typed the modifier key at all.

So, for example, let's say I want "sticky shift":

tap LSFT, tap a   -->  A
press LSFT, tap a, release LSFT  -->  A
tap LSFT, (wait), tap a  -->  a
tap LSFT, tap a, tap b   --> Ab

**Comment by slotThe** [comment]
I don't think we have this functionality yet.  There is `layer-delay`, but as the name says it's for layers and not for modifier keys.  I feel like this would be pretty easy with how we currently handle keys—I'll mark this as a feature request and will trry to look into it this weekend!

**Comment by slotThe** [comment]
@stevep99 I hacked something together on a [branch](https://github.com/slotThe/kmonad/tree/sticky-keys).

There's no documentation yet; you can use it like this:

``` clojure
(defalias
  lsty (sticky-key 500 lsft))
```

**Comment by stevep99** [comment]
Great! I'll see if I can build the project from that branch and report back!

**Comment by stevep99** [comment]
First, thanks for your efforts to implement this so quickly. I have compiled that branch, and tested the feature, and can confirm it works... _partially_!

I have tested using the following config:

```
(defalias 
  lsft_s (sticky-key 500 lsft)
  lctl_s (sticky-key 500 lctl)
)
```

The basic sticky function works:
- Shift followed by 'a' correctly produces A
- Control followed by 'a' correctly does a "select-all" (Ctrl-A)
- The timeout also seems to work.

What doesn't work, is typing while holding down the Sticky key:
- Holding Shift should allow typing Shifted characters as normal i.e. holding Shift while tapping "a a a a" should produce "A A A A". This is the way sticky keys are usually implemented.

A further feature, which I didn't clearly define in my initial comment, but would make the feature very powerful, is to able to combine sticky keys. So for example:
- "tap Shift, tap Control, tap a"  would produce Ctrl-Shift-A

As well as being a great feature for keyboard power users, this would also be a great accessibility feature for people with limited hand/finger movements.

In the interests of unambiguously specifying how the logic would work, let's consider some scenarios. In these, S is a Sticky key event and N is a normal key (non-sticky) event.

(1) S-down, S-up, N-down, N-up
The modifier is activated as normal on S-down. Upon S-up, the actual S-up event is delayed by the timeout, causing the modifier effect to remain in effect. When the N-down event happens, the modifier is still in effect.

(2) S-down, N-down, N-up, S-up
The sticky effect is not triggered because the N-down event happens before the S-up event. The N key is modified in the standard way. Any further keys typed after S-up will not be modified.

(3) S1-down, S1 up, S2-down, S2-up, N-down, N-up.
The stickyness is triggered for S1 *and* S2 as a non-sticky key wasn't hit until after the sticky-key's respective up-events.

Hope that helps to clarify the feature further, I can appreciate that once you get into the details it's not such a trivial feature!

**Comment by slotThe** [comment]
> What doesn't work, is typing while holding down the Sticky key:
> 
>     * Holding Shift should allow typing Shifted characters as normal
>       i.e. holding Shift while tapping "a a a a" should produce "A A A
>       A". This is the way sticky keys are usually implemented.

Ah, interesting; I didn't think of this.  Should the key still be sticky
afterwards?  I.e., what should

    P-Sft T-a R-Sft T-a
    
result in, `AA` or `Aa`?  The first behaviour sounds relatively trivial
to implement, the second one would probably need some further thinking.

> A further feature, which I didn't clearly define in my initial
> comment, but would make the feature very powerful, is to able to
> combine sticky keys.

That _does_ sound very interesting actually.  I'm not sure we have an
easy way to differentiate exactly which key is being pressed because we
only get the raw keycode and that could of course be remapped to
something else, but I'll look into this.

**Comment by stevep99** [comment]
> `P-Sft T-a R-Sft T-a`

I believe the correct method is that if Shift is held down and something else is typed, it behaves entirely in the standard way with no stickyness. So in this example, it should produce `Aa`. That sounds unfortunate if it's the more complicated option.

I think the solution may be that the stickyness should only be triggered on the key-up event, not the key-down event. So you'd basically be saying, has another key been typed since this key's down event? If no, apply sticky. If yes, don't apply sticky.

> That does sound very interesting actually. I'm not sure we have an
easy way to differentiate exactly which key is being pressed because we
only get the raw keycode

Yes, I thought this might be tricky. I was wondering if you could handle this by knowing which incoming keycode events have sticky-key mappings associated with them and which don't, and then the behaviour would be determined accordingly...

**Comment by slotThe** [comment]
On Sat, Mar 27 2021 07:01, Steve P wrote:
> I believe the correct method is that if Shift is held down and
> something else is typed, it behaves entirely in the standard way with
> no stickyness. So in this example, it should produce `Aa`. That sounds
> unfortunate if it's the more complicated option.
>
> I think the solution may be that the stickyness should only be
> triggered on the key-up event, not the key-down event. So you'd
> basically be saying, has another key been typed since this key's down
> event? If no, apply sticky. If yes, don't apply sticky.

Oh you're right, of course.  I was thinking a more difficult setup, but
this is essentially what we're currently doing with some of the
tap-style buttons.  Should be very doable! 

> Yes, I thought this might be tricky. I was wondering if you could
> handle this by knowing which incoming keycode events have sticky-key
> mappings associated with them and which don't, and then the behaviour
> would be determined accordingly...

We could certainly introduce a new bit of state for that; I'm not sure
if that's the right approach but it would _probably_ work.  Will need to
think about this a bit more

**Comment by slotThe** [comment]
On Sat, Mar 27 2021 15:22, Solid wrote:
> Oh you're right, of course.  I was thinking a more difficult setup, but
> this is essentially what we're currently doing with some of the
> tap-style buttons.  Should be very doable! 

This is now implemented, if you want to try it

**Comment by stevep99** [comment]
Yes, I have tested and can confirm it seems to be working well!

The only small quibble is that it doesn't yet allow you to combine modifiers, it only remembers the most recent modifier e.g. `control, shift, a ` produces only `shift a`. But still, that's relatively minor - a nice-to-have rather than a must-have. The main objective is that you can create arbitrary sticky modifiers in any layer, which this patch supports. I will be actively using it in my configuration to evaluate it in a real-word situation in the coming days.

Thanks for your work on this, kmonad is a great project and you guys are awesome!
