### ISSUE TITLE
Some specific compose characters not working

### ISSUE THREAD

**Issue by stevep99** [david-janssen/kmonad#207]
I've been trying out the compose characters feature. It works great for the most part, but I came across a handful of characters which don't seem to be supported in kmonad, despite there being compose sequences available. 

Here are the characters I've noticed not working:
¢ 
≤ 
≥ 
↑ 
↓
(note ← → left/right arrows do work fine, it's only up/down that don't).

 [I'm talking about the printed arrow characters here, not the movement keys]

**Comment by MaxGyver83** [comment]
I've tested this with ¢ (`compose` `c` `/`) and ≤ (`compose` `<` `=`) and it worked. Which OS do you use? What is your compose key?

**Comment by stevep99** [comment]
I am using Ubuntu 20.04, my compose key is set to menu. 

If I type `compose c /` on the terminal I get ¢. But putting it in the mapping file in a deflayer section doesn't work. For each of the characters above, the failure varies:

For `¢`,  kmonad loads pub I get no output for the mapped key.
For the others, kmonad fails to load with following errors:
`≤` kmonad: Encountered 'Transparent' ouside of top-level layer
`≥` kmonad: Encountered 'Transparent' ouside of top-level layer
`↑` unexpected '↑' expecting ')' 
`↓` unexpected '↓' expecting ')'

Have you tried putting these characters directly in your mapping?

**Comment by slotThe** [comment]
On Sun, Apr 04 2021 06:51, Steve P wrote:
> I am using Ubuntu 20.04, my compose key is set to menu. 
>
> If I type `compose c /` on the terminal I get ¢. But putting it in the
> mapping file in a deflayer section doesn't work.

Sounds like they're not in `KMonad.Keyboard.ComposeSeq' for some reason.
Would you mind posting the compose sequences for the respective symbols?

**Comment by stevep99** [comment]
The first three are these:
```
<Multi_key> <c> <slash>          	: "¢"   cent # CENT SIGN
<Multi_key> <less> <underscore>                 : "≤"   U2264   # < _ LESS-THAN OR EQUAL TO
<Multi_key> <greater> <underscore>              : "≥"   U2265   # > _ GREATER-THAN OR EQUAL TO

```
The up and down arrows are U2191 and U2193, but I can't seem to find compose sequences for them. Weirdly, you can apparently get *further, even more complicated* arrow compose characters using U2191 and U2193, such as:

`<Multi_key> <U2191> <minus>                     : "⍏"   U234f   # ↑ - APL FUNCTIONAL SYMBOL UPWARDS VANE`

But compose sequences to get the simple up arrow seem missing unless I'm mistaken. Perhaps an oversight somewhere.

**Comment by slotThe** [comment]
Okay I opened #208 for the ones with compose sequences; can you confirm that these work now?  Since the up/down arrows do not seem to have sequences, we can't currently emit them with the way we're doing unicode
