### ISSUE TITLE
Running multiple kmonad processes concurrently

### ISSUE THREAD

**Issue by thoelze1** [david-janssen/kmonad#214]
As I mentioned in #213, concurrent processes work on macOS (I think). Is this the case on Windows and Linux as well?

**Comment by MaxGyver83** [comment]
On Linux, yes. I do it every day that way.

**Comment by david-janssen** [comment]
Um... I think this issue is a statement of:

`This cool thing works cross-platform` so I'm closing it on account of... Great Success?
