### ISSUE TITLE
Enter key held down infinitely

### ISSUE THREAD

**Issue by zac-ng** [david-janssen/kmonad#215]
When I run the program, the enter is held down until I press escape.  This means that if I try typing in a document, the it continuously creates a new line.  Not sure if anyone else is facing the same issue.  Also is typing lag normal when running the program?  I'm not sure if it's because all of my tap-hold's.

This is my config file;

(defcfg
  	input  (device-file "/dev/input/by-path/pci-0000:2d:00.3-usb-0:3:1.0-event-kbd")
  	output (uinput-sink "My KMonad output" "/bin/sleep 2 && /bin/setxkbmap -option compose:ralt")
  
	;; Comment this is you want unhandled events not to be emitted
  	fallthrough true
  	;; Set this to false to disable any command-execution in KMonad
  	allow-cmd true
)

(defsrc
  grv  1    2    3    4    5    6    7    8    9    0    -    =    bspc
  tab  q    w    e    r    t    y    u    i    o    p    [    ]    \
  caps a    s    d    f    g    h    j    k    l    ;    '    ret
  lsft z    x    c    v    b    n    m    ,    .    /    rsft
  lctl lmet lalt           spc            ralt rmet cmp  rctl
)

(deflayer qwerty
  @shift`  @shift1    @shift2    @shift3    @shift4    @shift5    @shift6    @shift7    @shift8    @shift9    @shift0    @shift-    @shift=    bspc
  tab  @shiftQ    @shiftW   @shiftE  @shiftR  @shiftT  @shiftY  @shiftU  @shiftI  @shiftO  @shiftP   @shift[    @shift]    @shift\
  rctl @shiftA   @shiftS  @shiftD  @shiftF  @shiftG  @shiftH  @shiftJ  @shiftK  @shiftL   @shift;    @shift'    ret
  lsft @shiftZ  @shiftX  @shiftC  @shiftV  @shiftB  @shiftN  @shiftM   @shift,    @shift.    @shift/    rsft
  lctl lmet lalt           spc            ralt rmet cmp caps
)

(defalias
	shiftA (tap-hold 200 a A)
	shiftB (tap-hold 200 b B)
	shiftC (tap-hold 200 c C)
	shiftD (tap-hold 200 d D)
	shiftE (tap-hold 200 e E)
	shiftF (tap-hold 200 f F)
	shiftG (tap-hold 200 g G)
	shiftH (tap-hold 200 h H)
	shiftI (tap-hold 200 i I)
	shiftJ (tap-hold 200 j J)
	shiftK (tap-hold 200 k K)
	shiftL (tap-hold 200 l L)
	shiftM (tap-hold 200 m M)
	shiftN (tap-hold 200 n N)
	shiftO (tap-hold 200 o O)
	shiftP (tap-hold 200 p P)
	shiftQ (tap-hold 200 q Q)
	shiftR (tap-hold 200 r R)
	shiftS (tap-hold 200 s S)
	shiftT (tap-hold 200 t T)
	shiftU (tap-hold 200 u U)
	shiftV (tap-hold 200 v V)
	shiftW (tap-hold 200 w W)
	shiftX (tap-hold 200 x X)
	shiftY (tap-hold 200 y Y)
	shiftZ (tap-hold 200 z Z)
	shift` (tap-hold 200 ` ~)
	shift1 (tap-hold 200 1 !)
	shift2 (tap-hold 200 2 @)
	shift3 (tap-hold 200 3 #)
	shift4 (tap-hold 200 4 $)
	shift5 (tap-hold 200 5 %)
	shift6 (tap-hold 200 6 ^)
	shift7 (tap-hold 200 7 &)
	shift8 (tap-hold 200 8 *)
	shift9 (tap-hold 200 9 \()
	shift0 (tap-hold 200 0 \))
	shift- (tap-hold 200 - \_)
	shift= (tap-hold 200 = +)
	shift[ (tap-hold 200 [ {)
	shift] (tap-hold 200 ] })
	shift\ (tap-hold 200 \ |)
	shift; (tap-hold 200 ; :)
	shift' (tap-hold 200 ' ")
	shift, (tap-hold 200 , <)
	shift. (tap-hold 200 . >)
	shift/ (tap-hold 200 / ?)
)

**Comment by mklcp** [comment]
That too happens to me, but not only the enter key, sometimes other keys too

Here is a simpler config that systematically trigger that bug right from the start for me:

````

(defcfg
  ;; ** For Linux **
  input  (device-file "/dev/input/by-path/platform-i8042-serio-0-event-kbd")

  output (uinput-sink "∞ ⏎")

  fallthrough true
)


(defsrc
	q s spc
)


(deflayer base
	q s spc
)

````

**Comment by zac-ng** [comment]
This occurs to me regardless of what the config I use.  I tried the configs you had, but I still ran into the infinite error button bug.

**Comment by slotThe** [comment]
Sounds like your Return keys is captured for some reason.  Can you try doing something like `sleep 1 && kmonad /path/to/config`?

**Comment by mklcp** [comment]
`sleep 1 && kmonad /path/to/config` works without the bug
Maybd kmonad loads too fast and grab the enter key used for running the command

**Comment by slotThe** [comment]
Good to hear :) 

I thought we did something clever to avoid this sort of situation.  I'll close this as solved for now, though a note is made to revisit that part of the code at some point

**Comment by david-janssen** [comment]
Realized that some of the clever stuff we were considering doesn't actually solve this problem. Ended up adding a configurable startup-delay to kmonad itself, so we don't have to be so circumspect in launching it. We still have to make sure to not be holding any keys on the keyboard we wish to remap the exact moment that kmonad executes its grab, and I haven't figured out a way around this yet.

See #233
