### ISSUE TITLE
How to add the letter ñ

### ISSUE THREAD

**Issue by CRAG666** [david-janssen/kmonad#224]
I actively write in Spanish and I need the letter ñ but I don't know how to add it

**Comment by molleweide** [comment]
Hi, on my macbook pro I do `lalt n` with kmonad. ñ.

**Comment by molleweide** [comment]
Just to be clear kmonad does not output ñ if you add it to a keymap?

**Comment by MaxGyver83** [comment]
I have tried it with this minimal config:

```clojure
(defcfg
  ;; For Linux
  input  (device-file "/dev/input/by-path/platform-i8042-serio-0-event-kbd")
  output (uinput-sink "KMonad output"
    "/bin/sleep 1 && /bin/setxkbmap us -option compose:ralt")

  fallthrough true
)

(defsrc          n)
(deflayer level1 ñ)
```

This makes the `n` key emit `ñ`.

@CRAG666 : Do you use Linux?

**Comment by david-janssen** [comment]
Yah, just putting `ñ` in should work. I'm gonna close this for now since we haven't heard anything from @CRAG666 in a while. If the issue persists, feel free to give us another shout.
