### ISSUE TITLE
Wait/delay in macros

### ISSUE THREAD

**Issue by mwgkgk** [david-janssen/kmonad#23]
Motivation: quick gui-affecting macros sometimes need a short pause between keys, or have all keys be emitted with a configurable delay.
```
// Thunderbird: next unread folder. Here, 50 is a custom delay:
@m7 = 50 (( S-tab down n ))
```
 Workaround is to use a more suitable tool for the job, which is xdotool:
```
xdotool key --delay 50 shift+Tab Down n
```
Is this something that would ultimately be in scope for kmonad? Reasoning being that hooking up xdotool involves creating a custom script and passing a custom unoccupied key from kmonad to sxhkd to dispatch on, for what ultimately isn't much different from the other kmonad macros existing in the same layer :)

**Comment by david-janssen** [comment]
Absolutely. This shouldn't be too hard to include at all. The last few weeks have been very busy with other projects, but I will definitely put this on the list and let you know when this feature has been included.

**Comment by mwgkgk** [comment]
Absolutely not urging you to hurry, sir. Issues I've opened are idle wishful thinking. I love kmonad and wish the project longterm health.

**Comment by david-janssen** [comment]
Um.. oops. I implemented this ages ago and forgot to close the issue. We now parse `P##` as a pause for `##` ms.

An excerpt from my own config:
```
(defalias

  ;; Emacs macros (pauses are required for Emacs to catch on)
  P    P10 ;; Seems to be the sweet-spot
  swp  #(esc @P spc @P / @P /  )
  p/   #(esc @P spc @P p @P /  )
  svf  #(esc @P :   @P w @P ret)
```

Note, you don't have to do the `@P` trick to alias your pause. `#(a P5 b P10 c P15 d P20 e)` also works fine.

**Comment by david-janssen** [comment]
Oh, I should mention: this is on the refactor branch.
