### ISSUE TITLE
karabiner installed without kmonad kext

### ISSUE THREAD

**Issue by molleweide** [david-janssen/kmonad#230]
on my second macbook pro, 2013, i noticed that it is not using the kext that is required for kmonad but it seems to work anyways. I am testing building the bundled kext from source. I just wanted to mention in case same for somebody else.

**Comment by thoelze1** [comment]
What do you mean exactly?

**Comment by molleweide** [comment]
Yo!
Now I am writing on laptopA which had the correct kext installed.
On my laptopB the kext is not installed with Karabiner it seems and so when I run `kextstat | grep Karabiner` nothing shows but it did on laptopA (if I recall). So I have now built the bundled kext that comes with kmonad. I thought this would do it, but now I am stuck on computer saying I have to give permissions in sys pref to the kext but for me the kext is not showing up in the sys prefs.
However, you wrote in #105 that one shouldn't need to assign this permission. This is where I am now. 
I'll be investigating further.

**Comment by molleweide** [comment]
I'm gonna post the err msg in case it tells you something interesting.

**Comment by molleweide** [comment]
```sudo /sbin/kextload /Library/Application\ Support/org.pqrs/Karabiner-VirtualHIDDevice/Extensions/org.pqrs.driver.Karabiner.VirtualHIDDevice.v061000.kext

Password:
Executing: /usr/bin/kmutil load -p /Library/Application Support/org.pqrs/Karabiner-VirtualHIDDevice/Extensions/org.pqrs.driver.Karabiner.VirtualHIDDevice.v061000.kext
Error Domain=KMErrorDomain Code=27 "Extension with identifiers org.pqrs.driver.Karabiner.VirtualHIDDevice.v061000 not approved to load. Please approve using System Preferences." UserInfo={NSLocalizedDescription=Extension with identifiers org.pqrs.driver.Karabiner.VirtualHIDDevice.v061000 not approved to load. Please approve using System Preferences.}
```

**Comment by molleweide** [comment]
hmmm, yeah and I also haven't logged into my appleid account on laptopB.

**Comment by molleweide** [comment]
I am also a newbie to building and signing stuff so I am conflating terms I realize. So I have read through again and test so I am not missunderstanding.

**Comment by thoelze1** [comment]
> it seems you can not

Technically you *can* build the kext, you just have to be willing to disable SIP or pay for a Apple Developer ID with kext provisioning

> But then I don't understand why it hasn't been installed by Karabiner?

Why what hasn't been installed by Karabiner?

> Do you run Big sir?

I run Catalina but am in the process of moving to linux

**Comment by molleweide** [comment]
> Why what hasn't been installed by Karabiner?
> 
> >

I don't understand why the kext is not installed by Karabiner?

Also I see that a binary exists in the Karabiner kext repo but as you say I won't be able to use that one either it seems then.

Hmm yeah I am also trying to transition over to linux asap.

**Comment by molleweide** [comment]
also thanks for replying man!

**Comment by molleweide** [comment]
I'm going to try using the signed binary later because it seems it should maybe work then.
Because it seems you can still run legacy kexts on big sur if understand correctly.
I'ma find out.

**Comment by molleweide** [comment]
I'll close this after trying the shipped signed

> From a [comment](https://github.com/david-janssen/kmonad/issues/67#issuecomment-688552251)
> 
> > kexts can be built (but not loaded) without an "Apple Developer ID"

I did not see that this was a link. Now I see that you are all talking about the issue. Great. I'll read through all of this.

**Comment by david-janssen** [comment]
Really not sure about all this Mac stuff, therefore asking: can I close this? Or is this still an ongoing issue?

**Comment by molleweide** [comment]
yeah I am not super used to browsing through github so I missed the ongoing discussion you guys were having.
