### ISSUE TITLE
Creates endless rows of blank lines after execute 

### ISSUE THREAD

**Issue by premell** [david-janssen/kmonad#232]
Whenever i run sudo kmonad /kmonad.kbd I get endless rows of blank rows. I saw an earlier issue where the maintainer suggested "sleep 2 && kmonad ..." but this just froze my computer. Ive also noticed that if i control z during the process of printing blank rows my keyboard stops working completley

EDIT: Apperently it only keeps printing lines until I press another button, however the execution of the program never stops. The kmonad keybindings work, however I think its intended for kmonad to just execute and then return to the cmd

EDIT 2: So if i cancel the execution my keyboard becomes unresponsive until i reboot, however if I simply close the program during execution I keep the keybinds and the keyboard continues to work. However, if i closed the program I am unable to restart the program as I get the error: 
"kmonad: Could not perform IOCTL grab on: /dev/input/by-id/usb-Ducky_Ducky_One2_SF_RGB_DK-V1.01-190709-event-kbd"

**Comment by MaxGyver83** [comment]
Could you post your config file here?

**Comment by MaxGyver83** [comment]
> However, if i closed the program I am unable to restart the program as I get the error: 
> "kmonad: Could not perform IOCTL grab on: /dev/input/by-id/usb-Ducky_Ducky_One2_SF_RGB_DK-V1.01-190709-event-kbd"

Maybe another instance of kmonad is still running!?

**Comment by premell** [comment]
Hi this is my config: 
```

(defcfg
    
  input (device-file "/dev/input/by-id/usb-Ducky_Ducky_One2_SF_RGB_DK-V1.01-190709-event-kbd")
  output (uinput-sink "KMonad output")
  cmp-seq cmp


  fallthrough true
  allow-cmd true
)
#| -------------------------------------------------------------------------------------------

(defsrc
  esc      1     2     3     4     5     6     7     8     9     0     -    ´     bspc    del
  tab      q     w     e     r     t     y     u     i     o     p     å    ¨            pgup
  bspc     a     s     d     f     g     h     j     k     l     ö     ä    '     ret    pgdn
  lsft  lsgt     z     x     c     v     b     n     m     .     ,     -   rsft     up
  lctl  lmet  lalt              spc               ralt  rmet  rctl            left down right 
)
|#

(defsrc
  grv   1    2    3    4    5    6    7    8    9    0    -    =    bspc
  tab   q    w    e    r    t    y    u    i    o    p    [    ]    ret
  caps  a    s    d    f    g    h    j    k    l    ;    '    \
  lsft 102d  z    x    c    v    b    n    m    ,    .    /    rsft
  lctl lmet lalt            spc                 ralt rmet cmp  rctl
)




(defalias
    appL (tap-hold 200 a x)    
)

;;awful.tag.viewprev,


(deflayer tapDancingTest
  grv   1    2    3    4    5    6    7    8    9    0    +    =    bspc
  tab   q    w    e    r    t    y    u    i    o    p    [    ]    ret
      caps  @appL    s    d    f    g    h    j    k    l    ;    '    \
  lsft 102d  z    x    c    v    b    n    m    ,    .    /    rsft
  lctl lmet lalt            spc                 ralt rmet cmp  rctl
)



#|
(deflayer tapDancingTest
  esc      1     2     3     4     5     6     7     8     9     0     +    ´     bspc    del
  tab      @appL     w     e     r     t     y     u     i     o     p     å    ¨            pgup
  bspc     a     s     d     f     g     h     j     k     l     ö     ä    '     ret    pgdn
  lsft  102d z     x     c     v     b     n     m     .     ,     -   rsft     up
  lctl  lmet  lalt              spc               ralt  rmet  rctl            left down right 
)
|# 
```
There might be another instance running however nothing showed up when searching "kmonad" in stxcer

**Comment by MaxGyver83** [comment]
Your config doesn't look unusual. Are these block comments with `#|` and `|#` supported?
Maybe your `sudo kmonad` is still running in the background but not visible in stacer? You could try `pgrep -fa kmonad`.

**Comment by premell** [comment]
Hmm i dont seem to be able to reproduce the behavior I had before regarding closing kmonad and being unable to start it again. However I tried to removing all comments in my config file but it prints blank spaces after I execute until i type another letter. And it never finishes running 
![image](https://user-images.githubusercontent.com/65544203/117968134-24a73880-b326-11eb-9006-7770d7a6547c.png)

**Comment by MaxGyver83** [comment]
I don't know why this happens. Have you tried adding `"sleep 1 && setxkbmap ..."` to your `defcfg` block (like in the configuration tutorial)? And you shouldn't need to run kmonad with `sudo`.

**Comment by premell** [comment]
I get this message whenever I dont use sudo 
![image](https://user-images.githubusercontent.com/65544203/117972442-743c3300-b32b-11eb-9da7-35278c4c85e0.png).

![image](https://user-images.githubusercontent.com/65544203/117972499-861dd600-b32b-11eb-9d65-2cb0581381e1.png)
Now sleeps seems to stop the issue of repeating blank lines, however it stilll wont finish executing.

adding the sleep as shown in the config tutorial does not seem to change anything

**Comment by MaxGyver83** [comment]
> I get this message whenever I dont use sudo
> ![image](https://user-images.githubusercontent.com/65544203/117972442-743c3300-b32b-11eb-9da7-35278c4c85e0.png).

OK, then you probably haven't added yet your user to the `uinput` group. → See the [FAQ](https://github.com/david-janssen/kmonad/blob/master/doc/faq.md#q-how-do-i-get-uinput-permissions).

> ![image](https://user-images.githubusercontent.com/65544203/117972499-861dd600-b32b-11eb-9d65-2cb0581381e1.png)
> Now sleeps seems to stop the issue of repeating blank lines, however it stilll wont finish executing.
> 
> adding the sleep as shown in the config tutorial does not seem to change anything

Maybe it only works with the full path to `sleep` (on my system it's `/usr/bin/sleep`).

**Comment by david-janssen** [comment]
Actually, I think the `uinput` group is only required to start the `uinput` output device, while the issue seems to be with acquiring the input device.

If I `ls -l` my `/dev/` directory, it has many lines like:
> crw-rw---- 1 root input 13, 64 May 12 14:21 event0
Here the 'root input' bit signifies the owning user is 'root', but the group is 'input'.

If I then check the output of `groups` it says:
> users wheel audio video input nixconf uinput

So the group permission set on the keyboard files is actually that of a group that I, as a user, belong to. The fix for the `sudo` issue would be to identify the permissions on you `/dev/eventXX` filex, and make sure your user is part of that group.

NOTE: The `/dev/input/by-id` files are all symlinks with `root root` permissions, but they point at the `/dev/eventXX` files, and those are the actually pertinent permissions.

**Comment by david-janssen** [comment]
Oh, and in regards to the 'many blank lines' problem, that usually happens because you press `return` to start `kmonad`, and then `kmonad` starts and intercepts the release. The best way around this is to simply start `kmonad` like this: `sleep 0.1 && kmonad ...`, this is not required if launching kmonad from a script. Additionally, this should be fixed at some point. It's on my very long list of things that I should get to eventually :)

**Comment by david-janssen** [comment]
Actually, gonna close this now, because I think we've addressed the questions. If I'm wrong and stuff still doesn't work, just let us know and we'll reopen.
