### ISSUE TITLE
Starting KMonad by pressing Enter causes a state of 'Enter is pressed forever'

### ISSUE THREAD

**Issue by david-janssen** [david-janssen/kmonad#233]
This is an issue that is popping up everywhere, that is so simple a fix that I've been delaying it searching for bigger things. Let's fix this Soon(tm).

**Comment by david-janssen** [comment]
Well Mr. Janssen, I've taken the bug you've assigned me and succesfully formulated a fix: This issue should probably be fixed now:

e80800af078ec694228fefd7afa81d3476fa4f77

Hope this was Soon(tm) enough.

**Comment by thoelze1** [comment]
Great teamwork you two!

**Comment by thoelze1** [comment]
@david-janssen This SO [thread](https://stackoverflow.com/questions/3649874/how-can-i-get-the-keyboard-state-in-linux) has a way of detecting which keys are currently down. What do you think of using this method, before kmonad runs, to launch kmonad once all keys have been released? If this feature makes sense I'll try implementing it

**Comment by david-janssen** [comment]
@thoelze1 

It sounds like a big solution to a small problem. The issue here being that the SO thread describes a Linux solution and involves a lot of C code. So to make this a general feature we'd end up writing a lot of multi-platform C-code to fix a problem that is fixed for 99% with a 500ms wait :-).

I'm not going to stop you if you feel brave, but it's not the kind of problem I enjoy working on ;)
