### ISSUE TITLE
Increase polling rate

### ISSUE THREAD

**Issue by LamprosPitsillos** [david-janssen/kmonad#235]
I set my polling rate with `xset -r rate *** ***` 
But when using Kmonad it over-rights it...
Is there a way to configure this?
Thank you! 
And hope you are doing well David!

**Comment by MaxGyver83** [comment]
You can set this inside your config's `defcfg` block. Mine contains this:

```clojure
  output (uinput-sink "KMonad output"
    "/bin/sleep 1 && setxkbmap de -option compose:rctrl && xset r rate 300 50")
```

**Comment by david-janssen** [comment]
Hey cool, didn't even know this myself :).
