### ISSUE TITLE
Haddock fails

### ISSUE THREAD

**Issue by evertedsphere** [david-janssen/kmonad#29]
I believe this newline is the problem:

https://github.com/david-janssen/kmonad/blob/13cf1f6178357dfe44772e3d4bebc79be6cc8283/src/KMonad/Core/Parser/Token.hs#L98-L100

**Comment by david-janssen** [comment]
Well spotted!

> I believe this newline is the problem:
Almost, it was actually the `-- |` before the newline. Commented out one of the ADT constructors and accidentally created broken haddock syntax.

Anyways, fixed now, thanks for the headsup.

**Comment by evertedsphere** [comment]
Thanks! I might try to get a NixOS package for kmonad merged this week.

**Comment by david-janssen** [comment]
Waaahh, that would be great. I use nixos myself, and having 'kmonad' as
part of it would be awesome :-D

**Comment by evertedsphere** [comment]
right! i bet you have something like this
<https://github.com/evertedsphere/maschinen/blob/master/zzz/overrides/kmonad.nix>
already in your config together with some udev/kernel setup like this
<https://github.com/evertedsphere/maschinen/blob/master/zzz/keyboard.nix>?

**Comment by david-janssen** [comment]
You'd think that, but nope :). I just start it from a terminal and hope for
the best. Didn't feel inclined to mess around with NixOS yet.
