### ISSUE TITLE
openFd Permission denied

### ISSUE THREAD

**Issue by ssbothwell** [david-janssen/kmonad#35]
Hi. I'm trying to get `kmonad` working on `nixos`. I read the discussion [here](https://github.com/david-janssen/kmonad/issues/28). I've added the `uinput` kernel module and added myself to the `input` group.

When I attempt to run `kmonad`:
```
$ sleep 2 && kmonad .local/etc/kmonad.kbd
/dev/uinput: openFd: permission denied (Permission denied)
Encountered raw IO Exception attempting restart
```

`/dev/uninput` is owned by `root:root`. Should I set the group ownership to `input`?

**Comment by scottrosenquist** [comment]
Hey, my experience has been (and I've tried a bunch of things) that I could never get it to work without running it as root.

**Comment by ssbothwell** [comment]
I completely missed [this section](https://github.com/david-janssen/kmonad#uinput-permissions) of the docs. I'm setting up a `uninput` group with `udev` rules now. If I get it working, i'll paste a snippet of my `configuration.nix` for others to follow in the future.

**Comment by xcapegoat** [comment]
On arch I had to use input group as stated in the doc, then in /lib/udev/rules.d/40-input.rules I added:

KERNEL=="input", MODE="0660", GROUP="input", OPTIONS+="static_node=input"

**Comment by ssbothwell** [comment]
`/dev/uinput

**Comment by ssbothwell** [comment]
So on my machine,  `dev/uinput` is owned by the `uinput` group and `/dev/input/event*` is owned by the `input` group.

I added the following two udev rules and my user to both groups:
```
KERNEL=="uinput", MODE="0660", GROUP="uinput", OPTIONS+="static_node=uinput"
KERNEL=="input", MODE="0660", GROUP="input", OPTIONS+="static_node=input"
```
 
I'm still getting the same permission error:

**Comment by ssbothwell** [comment]
OK I got it working. For any other nixos users, here is what worked for me:

1. Create a `kmonad` derivation that pulls the static binary from github:
```
let
  pkgs = import <nixpkgs> { };

  kmonad-bin = pkgs.fetchurl {
    url = "https://github.com/david-janssen/kmonad/releases/download/0.3.0/kmonad-0.3.0-linux";
    sha256 = "4545b0823dfcffe0c4f0613916a6f38a0ccead0fb828c837de54971708bafc0b";
  };
in
  pkgs.runCommand "kmonad" {}
    ''
      #!${pkgs.stdenv.shell}
      mkdir -p $out/bin
      cp ${kmonad-bin} $out/bin/kmonad
      chmod +x $out/bin/*
    ''
```
2. Load the kmonad derivation in `configuration.nix` using a `let` block:
```
let 
    kmonad =  import /path/to/kmonad.nix;
in { 
  ...
}
```
3. Add the `uniput` kernel module to `configuration.nix`:
```
  boot.kernelModules = [ "uinput" ];
```
3. create a `uinput` group in `configuration.nix:
```
  users.groups = { uinput = {}; };
```
4. Add your user to `input` and `uinput` groups:
```
  users.extraUsers.myUser = {
    home = "/home/myUser";
    extraGroups = [ "audio" "docker" "networkmanager" "wheel" "input" "uinput" ];
    ...
}
```
5. Add the udev rule for `uinput`:
```
  services.udev.extraRules =
    ''
      KERNEL=="uinput", MODE="0660", GROUP="uinput", OPTIONS+="static_node=uinput"
    '';
```
6. Reboot and launch kmonad with your config. : )

I can clean up these instructions and add them as a PR to the docs if desired.

**Comment by david-janssen** [comment]
Happy to hear you got it running. If you could add the instructions to the docs that would be great! I await your PR :-)

**Comment by j-steinbach** [comment]
@solomon-b: regarding step 3, is it `uniput` or `uinput`? (I am guessing the latter)
