### ISSUE TITLE
Variable remapping based on order of Release events?

### ISSUE THREAD

**Issue by thoelze1** [david-janssen/kmonad#38]
Hello and thanks for your work! I am trying to figure out if kmonad would allow me to bind a non-modifier character and a modifier to the same key, but with variable behavior based on the order of key releases. This behavior is similar that of TapNext, but with a slight difference. Here is my use case:

Suppose I want to bind `escape` and `control` to the key <kbd>CAPS LOCK</kbd>. Let's say that a Push event for <kbd>CAPS LOCK</kbd> has occurred, followed by a Push event for <kbd>J</kbd>. At this point, <kbd>CAPS LOCK</kbd> and <kbd>J</kbd> are currently depressed.

- If the Release event for <kbd>J</kbd> happens next, then I want `control` to be applied, and then `j` to be posted. Then, whenever the Release event for <kbd>CAPS LOCK</kbd> happens, I want `control` to be unapplied. The rationale for this behavior is that because <kbd>J</kbd> was both pressed and released while <kbd>CAPS LOCK</kbd> was held, I was intending to use <kbd>CAPS LOCK</kbd> as `control` here.

- If the Release event for <kbd>CAPS LOCK</kbd> happens next, then I want `escape` to be posted, immediately followed by `j`.  Then, when the key up for <kbd>J</kbd> happens, nothing additional happens. The rationale for this behavior is that I intended to send `escape` followed by `j`, but I was typing so quickly that I started to press <kbd>J</kbd> before I released <kbd>CAPS LOCK</kbd>.

I read the documentation and I couldn't tell if this behavior is impossible with kmonad, or if it's possible with layers but I just don't understand kmonad yet. This line in the [general concepts](https://github.com/david-janssen/kmonad/blob/master/doc/concepts.md) documentation makes me think it's not possible:

> When we register a Release event, the stack is not consulted at all. Instead we keep track of exactly which Button was used to handle a push-event for the corresponding keycode, and then use that same Button to handle the release-event.

I have been trying to achieve this behavior with several keyboard managers now, but I haven't been able to implement it with existing tools. Any help or advice would be appreciated! Thanks.

**Comment by david-janssen** [comment]
That's a very interesting use case that currently isn't possible with the buttons that exist. However, the function you describe can be modelled quite closely with a TapHold button with a short delay. The TapHold will decide what to be based on how quickly you release it, regardless of what happens with others keys, so if you simply intend to tap CapsLock, as long as the release happens in the provided timing window, it will register as a tap (and emit an Esc). The moment you hold it longer than the delay it switches into a Control.

The cool thing about the TapHold is that it will pause the processing of your events. So even if you end up pressing the J before CapsLock, KMonad will not emit anything until the TapHold is resolved (as either a tap or a hold). Once its decided it will resume processing.

Give it a try and see if that sufficiently fulfills your need. Lemme know how it goes.

**Comment by thoelze1** [comment]
Thanks for your help - I got kmonad running and taphold does almost exactly what I was looking for!  I understand what you mean about kmonad waiting to emit until the taphold is resolved. I love this behavior.

For what it's worth, my use case is actually binding the modifiers to the home row almost exactly like in [this issue](https://github.com/david-janssen/kmonad/issues/32) (I just wanted to keep my initial question simple).

I will also note I'm experiencing some weird behavior with a 200 ms taphold with `l` on tap and `alt` on hold. When I quickly tap the taphold key and quickly tap another key in rapid succession, then sometimes `alt` is thereafter permanently applied. Even stranger, sometimes `caps lock` is permanently turned on as well. I am using release 0.3.0. I noticed that some others (#26,#32) have had similar issues. From what I skimmed over, it looks like compiling from more recent source may help. I'll try tomorrow and post an update.

**Comment by thoelze1** [comment]
I followed #32 and compiled the refactor branch. It works great now. I've been using the updated binary for a few hours without any weird behavior. Thanks for this awesome software.

Are there notes for contributors that I can look at? I'm new-ish to Haskell but I'd like to see if there's anything I can contribute.

**Comment by david-janssen** [comment]
Happy to hear you got it working.

There are currently not a lot of notes. I am working on finalizing the refactor version of `kmonad`, there is still some cruft and some bad design decisions that I am cleaning up. Then I hope to release a final version (barring bugfixes), followed by a few articles about the design of `kmonad`, and how to make the step from writing toy examples to writing something medium sized (this was my first Haskell project longer than like... 40 lines :-).

**Comment by david-janssen** [comment]
Actually, guess I can close this.

**Comment by thoelze1** [comment]
Are you or is anyone else working on porting this to OS X?

**Comment by david-janssen** [comment]
No actually. However the code is organised in a way that is supposed to be as OS agnostic as possible. If you look at the C-code, we essentially need to be able to: capture control over an input keyboard and create some way of sending events to the OS again. I haven't got OSX here locally, so it is very hard to develop for it. If you are interested in giving it a try I'd be very happy to be available to answer any KMonad/Haskell related questions. All we really need is a C-file that exposes some functions that perform the above-mentioned tasks.
