### ISSUE TITLE
Leader key/layer momentary timer

### ISSUE THREAD

**Issue by rayslinky** [david-janssen/kmonad#39]
Would it be possible to designate a key to switch to a layer for the next 500 (or shorter) milliseconds, allowing toggling a layer momentarily, without holding a key and without switching to it? It could be the equivalent of how the leader key works in qmk.

**Comment by david-janssen** [comment]
Hey Ray,

That's a good idea. A bit busy at the moment but I hope to find some time in the middle of next week. Will keep you posted.

**Comment by david-janssen** [comment]
Hey Ray,

Sorry for the delay, I decided I wanted to make a very elegant solution and started implementing something *way* too complicated. Came to my senses just now and quickly added the functionality you requested in de85686be1a26cffa7e0dc1c2dcdffae452c86e8 in the `refactor` branch

There are 2 new buttons:
```
(layer-delay delay tag)
(layer-next tag)
```

Layer-delay does exactly what you asked, it will switch to a layer marked `tag` for `delay` ms.
Layer-next simply performs the next key press in the layer `tag` and then automatically switches back.

Lemme know if it works out for you.

**Comment by david-janssen** [comment]
Actually, I think this is fixed/done, so I might as well close this. Lemme know it this needs action.
