### ISSUE TITLE
How to avoid "Duplicate encountered in SRC layer" when keyboard has duplicate keys (split spacebar)

### ISSUE THREAD

**Issue by tjgordon** [david-janssen/kmonad#40]
How should I write a source layer for a keyboard with 2 space keys?  

Here is an image of the layout:

![fs2-blue-mac-oh](https://user-images.githubusercontent.com/7094859/86996286-17e31280-c160-11ea-8ea5-defd03338841.jpg)

Here is my in-progress `.kbd` file, which causes `Duplicate encountered in SRC layer`:  

```
INPUT = LINUX_DEVICE L64 /dev/input/event13

OUTPUT = UINPUT_SINK "Kinesis Freestyle2 Blue (Mac)"


SRC
  grv  1    2    3    4    5    6       7    8    9    0    -    =    bspc      home
  tab  q    w    e    r    t            y    u    i    o    p    [    ]    \    end
  caps a    s    d    f    g            h    j    k    l    ;    '    ent  pgup
  lsft z    x    c    v    b            n    m    ,    .    /    rsft up   pgdn
  lctl lalt lmet spc                              spc  rmet ralt left down rght


@lsp = TH 300 spc lctl
@rsp = TH 300 spc lsft
  
  
LAYER MAIN
  grv  1    2    3    4    5    6       7    8    9    0    -    =    bspc      home
  tab  q    w    e    r    t            y    u    i    o    p    [    ]    \    end
  caps a    s    d    f    g            h    j    k    l    ;    '    ent  pgup
  lsft z    x    c    v    b            n    m    ,    .    /    rsft up   pgdn
  lctl lalt lmet @lsp                             @rsp rmet ralt left down rght

```

When I use `evtest` to test the left space and right space, they both appear to be the same:  

```
Testing ... (interrupt to exit)
Event: time 1594264935.513920, type 4 (EV_MSC), code 4 (MSC_SCAN), value 70028
Event: time 1594264935.513920, type 1 (EV_KEY), code 28 (KEY_ENTER), value 0
Event: time 1594264935.513920, -------------- SYN_REPORT ------------
Event: time 1594264936.817861, type 4 (EV_MSC), code 4 (MSC_SCAN), value 7002c
Event: time 1594264936.817861, type 1 (EV_KEY), code 57 (KEY_SPACE), value 1
Event: time 1594264936.817861, -------------- SYN_REPORT ------------
 Event: time 1594264936.907872, type 4 (EV_MSC), code 4 (MSC_SCAN), value 7002c
Event: time 1594264936.907872, type 1 (EV_KEY), code 57 (KEY_SPACE), value 0
Event: time 1594264936.907872, -------------- SYN_REPORT ------------
Event: time 1594264940.302462, type 4 (EV_MSC), code 4 (MSC_SCAN), value 7002c
Event: time 1594264940.302462, type 1 (EV_KEY), code 57 (KEY_SPACE), value 1
Event: time 1594264940.302462, -------------- SYN_REPORT ------------
 Event: time 1594264940.392538, type 4 (EV_MSC), code 4 (MSC_SCAN), value 7002c
Event: time 1594264940.392538, type 1 (EV_KEY), code 57 (KEY_SPACE), value 0
Event: time 1594264940.392538, -------------- SYN_REPORT ------------
Event: time 1594264942.303683, type 4 (EV_MSC), code 4 (MSC_SCAN), value 700e0
Event: time 1594264942.303683, type 1 (EV_KEY), code 29 (KEY_LEFTCTRL), value 1
Event: time 1594264942.303683, -------------- SYN_REPORT ------------
Event: time 1594264942.393735, type 4 (EV_MSC), code 4 (MSC_SCAN), value 70006
Event: time 1594264942.393735, type 1 (EV_KEY), code 46 (KEY_C), value 1
Event: time 1594264942.393735, -------------- SYN_REPORT ------------

```

I'm hoping to have different mappings for left space and right space, but is that possible if both are the same key in `evtest`?

**Comment by david-janssen** [comment]
I'm afraid your situation does not have a solution. KMonad can only begin after the hardware signal has been received, so if you can't distinguish between buttons in the input signal, there is nothing we can do. (And indeed, `evtest` is a correct representation: if `evtest` can't tell the difference, neither can we).

I suggest you simply remove one of the space buttons in the input layer. This means both space buttons will always behave in exactly the same way, but at least you'll get a working config.

**Comment by tjgordon** [comment]
Thank you for the suggestion, it works fine with only one space. Since ergonomic keyboards with split spacebars are common, I think it might be helpful to indicate this in the documentation. Would you be interested in a PR adding a note about split spacebars, and if so, do you think it would fit better in the readme or the syntax guide?

**Comment by david-janssen** [comment]
Hey there,

A PR with a note would be appreciated, but ideally it would go under the `refactor` branch, since that it basically done (except for documentation). If you feel like it, go ahead and add a paragraph to 'configuration.md' there. However, if not, then I will try my best to remember to add note about this when I finally write the documentation :-)
