### ISSUE TITLE
Typing quickly with home row mods leads to out of order sequences

### ISSUE THREAD

**Issue by obar** [david-janssen/kmonad#44]
I'm playing around with the refactor branch, using the colemak layout from the example configuration, and the following home row mods on the pointer finger keys `t` and `n`:

```
(defalias
  tsh (tap-hold 200 t lsft)
  nsh (tap-hold 200 n lsft)
  )
```

This works great when typing slowly, but results in out-of-order of the tap-hold keys and whichever key follows when typing quickly. This seems to be the result of a key down of the following key coming before the key up of the tap-hold mod. The simplest **example of the issue** is typing `to` quickly. I get `ot` nearly every time, with the following output with debug-level messages:

```
--------------------------------------------------------------------------------
Received event: Press <f>
Running hooks
Registering hook: 5
Registering hook: 6

--------------------------------------------------------------------------------
Received event: Press <;>
Running hooks
Registering hook: 7
Registering hook: 8
Emitting: Press <o>
Registering hook: 9

--------------------------------------------------------------------------------
Received event: Release <f>
Running hooks
Emitting: Press <t>
Emitting: Release <t>
Registering hook: 10

--------------------------------------------------------------------------------
Received event: Release <;>
Running hooks
Emitting: Release <o>
Tried cancelling expired hook: 5
Tried cancelling expired hook: 7

--------------------------------------------------------------------------------
```

Is there a way to wait for a tap-hold release or the hold time being reached (whichever comes first) before emitting the next key codes?

Thanks for the useful package!

**Comment by david-janssen** [comment]
Hey Ori,

Yeah, TapHold is weird at the moment. I think I must've broken something recently. See #42 

I will try to get to this soon and fix it :)

**Comment by obar** [comment]
Ah sorry for the duplicate! I saw that issue but thought it was something to do with tap-hold and layers :) Thank you!

**Comment by obar** [comment]
I can confirm that this bug does not happen in fa09d6a

**Comment by david-janssen** [comment]
Oooh thanks, that's a useful tidbit of information. It really is the same bug as #42 then. I will close this, then we can centralize.
