### ISSUE TITLE
Need a test on 'testing' branch from Mac User

### ISSUE THREAD

**Issue by david-janssen** [david-janssen/kmonad#45]
Hey @thoelze1 (or other Mac user),

So I just merged your pull request, and everything looked fine to me, but in your description you mention that maybe some of your code was uselessly allocating and deallocing a string. I *think* I fixed that, my change can be found in the `testing` branch. Could you give it a go?

Cheers,

D

**Comment by thoelze1** [comment]
I'll try it now

**Comment by david-janssen** [comment]
Just made a fix.. forgot to free the var

**Comment by thoelze1** [comment]
Fixed in 6654396

**Comment by david-janssen** [comment]
Very good. Closing.
