### ISSUE TITLE
Modifiers behaving differently than OS in kmonad

### ISSUE THREAD

**Issue by theol0403** [david-janssen/kmonad#50]
First of all, thanks again for making this super cool project, it is very impressive and useful :smiley:. 

Hopefully I can explain this issue properly. I am using the refactor branch now.

With kmonad disabled, and the OS (linux) handling the keyboard, if I press a modifier and key in the following order, I get the modified key. For example:
 - <kbd>SHIFT</kbd> is pressed
 - <kbd>j</kbd> is pressed
 - <kbd>SHIFT</kbd> is released
 - <kbd>j</kbd> is released

In this example, my OS will emit <kbd>J</kbd>. However, kmonad emits <kbd>j</kbd>.

This has caused me to make a lot of typos, I write c++ code and all my double colons were being typed like <kbd>:;</kbd> :stuck_out_tongue:. This applies to all keys (special behaviour assigned to them or not), and all modifiers (like <kbd>CTRL</kbd>, etc). My customary action of <kbd>CTRL-S</kbd> by rolling my hand from <kbd>CTRL</kbd> to <kbd>S</kbd> does not work anymore, I now have to be deliberate to keep <kbd>CTRL</kbd> held *after* I release <kbd>S</kbd>.

I feel like this is a product of another difference from the OS, where a modded key is emitted on press instead of on release like with kmonad.

Anyways, I hope this made sense, and that a fix is doable. Thanks!

**Comment by obar** [comment]
For me this works fine, maybe you can say a little more.

Do you have those modifiers in both the src and base layer of your config? If not they won't be passed through. Also, are you using the refactor branch? It might be useful for you to include your config.

**Comment by theol0403** [comment]
I'm not sure what you mean by both in the src and base layer, but I believe so. The modifiers do work as long as I release the key before the modifier.

I am using the refactor branch. Here is my config:
https://github.com/theol0403/kmonad-layout/blob/master/refactor.kbd

I actually realized some more information. I thought I had tested it on non-button keys but I actually didn't.
So, this behaviour only happens with keys that have some button assigned to them like tap-hold. I think the issue happens because tap-hold buttons only emit their tap keycode on tap-release, and so by that time the modifier is no longer pressed.

I know a solution would be to make a layer for each modifier that removes the tap-hold of the home row keys, but
 - would be a pain to do
 - would prevent the modifiers from being emitted to the OS on layer change
 - keeping tap-hold functionality on the home row keys even with a modifier is useful

So the required solution would be to emit the modifiers that existed when the tap-hold was pressed when the tap-hold is released, instead of combining modifiers only when the tap-hold is released.

**Comment by theol0403** [comment]
I'm not sure what that would solve, but I tried it and I don't think it solved the issue. The issue remains that even though shift was pressed when the tap-hold key was pressed, if the tap-hold key is released after shift is released it won't be modified.

**Comment by david-janssen** [comment]
I think I see your problem, and your proposed solution, however, I am not sure if this is feasible, for a number of reasons:

1. All buttons basically work in complete isolation. They have no information available about anything but themselves. So adding this 'grab the environment' functionality would require a redesign of the core architecture.
2. This becomes even more complicated if you consider a 2nd tap-hold. Image a 'shift-esc' taphold being pushed to modify a 'ctrl-colon' taphold. Then the ctrl-colon taphold doesn't know whether it should log a shift or not. (Schroedinger's Keyboard :-)).
3. What environment should we capture? The entire keyboard state? I am currently working with a program that uses `insert` as a modifier key. This goes hand-in-hand with the fact that KMonad doesn't distinguish between modifiers and normal keys. In essence all KeyCodes are equal, we just deal with receiving and emitting them. We let the OS worry about semantics.

Let me think for a moment... Two solutions that fit well with the spirit/mechanisms of KMonad are:

1. A layer that adds shifted versions of the buttons. This is slightly different from what you propose. What you could do is this:
```
(defalias
  mysft (layer-toggle shifted)
  ;te (tap-hold 300 ; ralt)
  :te (tap-hold 300 : ralt))

(defsrc ; lsft)

(deflayer main @;te @mysft )

(deflayer shifted @:te _)
```
(NOTE: not in a position where I can actually try and run this code at the momen, so there might be some inconsistencies/syntax errors, but I hope the idea is clear: Shift becomes a layer where you manually shift all the taps, but leave the holds).

This should tick nearly all the boxes, no?

2. What I really enjoy when writing Haskell (which has loads of ->, >>=, <$> stuff) is my macro layers (check `atreus.kbd` in templates for a reference). So if you find yourself typin `::` alot, why not just bind it to 1 button?

**Comment by obar** [comment]
> I'm not sure what that would solve

You're right, that doesn't make sense. `around-next` could make the next key shifted but I'm not sure about the held behavior.

**Comment by david-janssen** [comment]
Did my proposed fix (1.) sufficiently address your issue? If so, I'd like to close this issue. If not, I'd like to know how we can be of further assistance.

**Comment by theol0403** [comment]
Hey, I've been pretty busy this week and haven't had much time to tinker with kmonad. I would not close this issue yet, I have some more things to say but don't have the time right now to articulate. Hopefully I'll have a chance to reply by next week.

If I understand correctly, your solution is what I described earlier, and these were my reasons I did not really want to do it:

> I know a solution could be to make a layer for each modifier that removes the tap-hold of the home row keys, but
> - would be a pain to do (for each modifier ie shift & ctrl)
> - would prevent the modifiers from being emitted to the OS
> - chaining modifiers would not work (ctrl-shift)
> - keeping tap-hold functionality on the home row keys even with a modifier is useful
 
And briefly my idea is to have a special button that marks a modifier, `(global-modifier)`, which then gives you a defined way of knowing which modifiers to capture during a tap-hold.

**Comment by david-janssen** [comment]
Hey there,

Thanks for giving me a headsup, we'll leave this open until we sort your issue, no need to rush whatsoever.

> If I understand correctly, your solution is what I described earlier.

Actually, I don't think so. You didn't provide a code sample with your proposed idea, so perhaps I am not following your proposal correctly, but you speak about disabling the tap-hold buttons in a separate layer. My proposed solution would not be to disable the tap-hold buttons at all, but to have a second layer with different tap-hold buttons in a shifting layer.

Perhaps it is easier if I use 'a' as an example:
```
(defalias
    sfd   (layer-toggle shifted)
    cta   (tap-hold 150 a ctl)
    ctA   (tap-hold 150 A ctl)
)

(deflayer base
  @sft @cta)

(deflayer shifted
  _    @ctA)
```

So, this runs into some of the issues you mention:
> would be a pain to do (for each modifier ie shift & ctrl)
But less so then changing the base architecture of kmonad.
> would prevent the modifiers from being emitted to the OS
Not sure I follow, you mean when you hold the button over the timeout and send a raw 'sft' to the OS? True, but this could be solved by making the layer-toggling button into, for example, a tap-next-hold like this:
`(tap-hold-next 150 lsft (layer-toggle shifted))`. Then if you tap the button you do actually send a shift to the OS, and when you hold, you get your extended shift functionality.
> chaining modifiers would not work (ctrl-shift)
True, although in your config you do still have raw modifiers away from homerow for such occurences, and if it happens often enough, you could make a special layer button just for ctrl-shifted buttons.
> keeping tap-hold functionality on the home row keys even with a modifier is useful
I don't follow, I think this does that.

Perhaps we are talking past eachother. Anyways, take your time, have a look when you are less busy. I'm around to help you brainstorm ways of making your config work.

Cheers!

D

**Comment by theol0403** [comment]
Hey, sorry for the long delay.
Yeah, I understand your solution, it should be enough to workaround everything I need if really put in the effort. Too bad that there is not an easy solution for either of us. 
My issue still happens consistently btw, it is probably a product of a cheap keyboard and bad habits :grin:.

However, I've finally got myself a QMK powered keeb, so I'll probably be moving away from this project for the time being. Feel free to close the issue.
Thanks again for the super cool project and your help! I'll definitely be keeping an eye on this for the future =)

**Comment by david-janssen** [comment]
No worries :-) Closing.

**Comment by meain** [comment]
Just wondering if there has been any progress made on this. This is the only tiny annoying thing at this point for me with the project. I have a bunch of the home row keys mapped to custom layers and using shift with any of them is as OP mentioned messes things up. I could probably create a custom layer for shift, but adding in all combinations in which shift can be presses would be quite a bit of work.

For example `ctrl+shift+j` would work but `shift+ctrl+j` might not.
