### ISSUE TITLE
KeyFn missing frm KeyCode.hs

### ISSUE THREAD

**Issue by KirinDave** [david-janssen/kmonad#6]
I noticed that the Fn key is missing from KeyCode.hs. Is there a reason for this? Given that Kmonad really shines on laptops and some of the most popular linux laptops ship an Fn key by default, it seems to me like a surprising omission.

**Comment by wismill** [comment]
This is because the `Fn` key [does not send a scancode](https://en.wikipedia.org/wiki/Fn_key#Technical_details) so it cannot be remapped.

**Comment by david-janssen** [comment]
Just confirming @wismill, the Fn key is handled internally to remap keycodes by the hardware before any event is ever sent to the OS. You can check this with `evtes` if you like. If it doesn't generate an `evtest` event, we can't map it.

It is probably a good idea to add a note about this to the documentation though, so thanks for the heads-up.
