### ISSUE TITLE
mention 'stack install' in installation.md

### ISSUE THREAD

**Issue by jganong** [david-janssen/kmonad#71]
i had never used stack before, so i did not realize i needed to do 'stack install' afer
'stack build', since the audience of that section is people like me, it would be helpful
to mention it.  thanks!

**Comment by david-janssen** [comment]
I had no idea either. `stack install` is a thing? That's cool :-). Will add it to the docs soon.

**Comment by david-janssen** [comment]
Done: d5b4d96387283959a900fb5e2ee3bd62526ac08e

**Comment by jganong** [comment]
thanks!
