### ISSUE TITLE
Publish on Hackage?

### ISSUE THREAD

**Issue by jacereda** [david-janssen/kmonad#73]
Nice tool! Could you add it to Hackage so it's easier to package?

https://github.com/NixOS/nixpkgs/issues/84550#issuecomment-611288901

**Comment by david-janssen** [comment]
Hey there. Absolutely, I'd be happy to. I am extremely busy the next week and a half, so I'm not sure I'll get to it. Moving between hemispheres :)

**Comment by david-janssen** [comment]
Did all the prep work for this, realized I need upload priveleges, emailed the Hackage trustees, waiting for response.

**Comment by david-janssen** [comment]
Got priveleges, running into issues uploading because of OS-specific code directories. Filed an issue, waiting for assistance.

**Comment by david-janssen** [comment]
Got it up: https://hackage.haskell.org/package/kmonad
