### ISSUE TITLE
`tap-next` key is ignored on fast typing

### ISSUE THREAD

**Issue by ivanjermakov** [david-janssen/kmonad#87]
example config:
```
(defalias
    a (tap-next a lsft)
)
(defsrc
    a b c
)
(deflayer default
    @a b c
)
```

Press: `a down, b down, a up, b up`
Result: `B`
Expected: `ab`

Press: `b down, a down, b up, a up`
Result: `b`
Expected: `ba`

Results compared with QMK

**Comment by MaxGyver83** [comment]
If you use `tap-next-release` instead of `tap-next`, you get the behaviour you expect.

With `tap-next-release` you only get a shift, when you do `a down, b down, b up, a up`.

**Comment by david-janssen** [comment]
@MaxGyver83 is spot on. The `tap-next` decides based on the next `Press` event, so in both your examples the `tap-next` functions as a `held` button, since the next event was always a different button.
