### ISSUE TITLE
Feature request: better basic description.

### ISSUE THREAD

**Issue by magnetophon** [david-janssen/kmonad#91]
I was linked to this project from a chat, but I could only kind of guess what this project does by it's name and the short description provided.

I suggest to start the readme with the description from hackage, or your reddit post. 

Also, I have no idea what you mean by onion in this context.
It made me think of TOR, but I don't think that is the meaning of onion you are referring to.

**Comment by david-janssen** [comment]
Noted. I used to have a README that was way too long and I moved most of the documentation to the tutorial, but you are right, a nice introduction on the front-page would be a good idea. 

In regards to the onion: it's a [Shrek reference](http://quotegeek.com/quotes-from-movies/shrek/7316/). I guess programmers are a bit too fond of inside jokes. 

Thanks for the heads-up, much appreciated. I will leave this open as a reminder to myself for when I find some time.

**Comment by dit7ya** [comment]
Hi. I can do a rewrite of the README. Let me know if you are planning to work on this, otherwise I will submit a PR in a couple of days.

**Comment by david-janssen** [comment]
@dit7ya Yah, I would appreciate that a lot. Finding it hard to find time to work on KMonad these last 2 weeks, and not sure if things will clear up in the next 2 weeks (here's to hoping for the best :)). So yeah, that would be great!

**Comment by slotThe** [comment]
@magnetophon what's the state of this issue?  Are you satisfied with @dit7ya's redesign of the readme, or is there anything still bothering you?

**Comment by magnetophon** [comment]
All clear, thanks @dit7ya!
