### ISSUE TITLE
Question: Restarting kmonad from command button

### ISSUE THREAD

**Issue by rosshadden** [david-janssen/kmonad#92]
I was trying to make a restart button but am running into a problem.

```lisp
(defalias
  rst (cmd-button "pkill kmonad; kmonad ~/dotfiles/src/.config/kmonad/config.kbd"))
```

When pressed, this gives the error:

```
kmonad: Could not perform IOCTL grab on: /dev/input/<my-keyboard>
```

I tried adding in a `sleep 1` in there in case it was a timing thing, but that didn't seem to help. I was thinking the commands would be run by the user than ran kmonad to begin with, and thus have the same permissions to uinput.

Any help on this would be greatly appreciated.

**Comment by MaxGyver83** [comment]
Maybe "pkill kmonad" failed and the keyboard is still being grabbed by the old process. I would try "pkill kmonad && kmonad ...".

**Comment by david-janssen** [comment]
Hey Ross,

You're trying to do a very interesting thing, and I am not sure how to achieve it. So, first of all, what does the error message mean? Well, you're trying to do an IOCTL-grab of some keyboard that is already grabbed. As @MaxGyver83 indicated, this is because the new KMonad is trying to start-up before the old one has released, and has nothing to do with permissions. If I remember correctly KMonad should just be 'fire-and-forgetting' these commands, and not waiting for them to return al all. But then it surprises me that throwing in a `sleep` doesn't help.

I'll have to experiment a bit to figure out exactly how it's going wrong and come up with a solution. I was already considering a built-in KMonad `reset` or `reload` command, that just reinits KMonad using the same command-line arguments it was started with. That would sort this whole issue.

I'm afraid I can't help you right-right now, though. Just went through a big move and currently have neither the time nor the RAM. I'll be rebuilding my PC sometime soon, and when things are a bit more settled I will definitely get to this.

**Comment by slotThe** [comment]
On Tue, Sep 22 2020 22:25, Ross Hadden wrote:
> ```
> kmonad: Could not perform IOCTL grab on: /dev/input/<my-keyboard>
> ```

This is a funny one.  What happens (at least as far as I can tell) is
that the new process inherits all the open file descriptors of the
kmonad process.  Listing all the open file descriptors with `lsof -p
KMONAD_PID`, we can see that this also includes the keyboard grab we are
performing.  In my case:

    COMMAND  PID USER   FD      TYPE DEVICE SIZE/OFF      NODE NAME
    [...]
    kmonad  6514 slot   23w      CHR 10,223      0t0     16656 /dev/uinput
    kmonad  6514 slot   24r      CHR  13,64      0t0     17434 /dev/input/event0

So essentially while kmonad is indeed killed, these file descriptors
stay open for as long as the command is running, resulting in a failed
restart.  Luckily, the `CreateProcess` type in `System.Process` (and its
`UnliftIO` equivalent, which we are using) has an option for closing all
file descriptors except for std{in,out,err}.  The following diff does
exactly that.

    diff --git a/src/KMonad/App.hs b/src/KMonad/App.hs
    index 2861da6..4997548 100644
    --- a/src/KMonad/App.hs
    +++ b/src/KMonad/App.hs
    @@ -18,7 +18,7 @@ where
    
     import KMonad.Prelude
    
    -import UnliftIO.Process (spawnCommand)
    +import UnliftIO.Process (CreateProcess(close_fds), createProcess_, shell)
     import RIO.Text (unpack)
    
     import KMonad.Action
    @@ -221,9 +221,13 @@ instance (HasAppEnv e, HasAppCfg e, HasLogFunc e) => MonadKIO (RIO e) where
         f <- view allowCmd
         if f then do
           logInfo $ "Running command: " <> display t
    -      void . spawnCommand . unpack $ t
    +      spawnCommand . unpack $ t
         else
           logInfo $ "Received but not running: " <> display t
    +   where
    +    spawnCommand :: MonadIO m => String -> m ()
    +    spawnCommand cmd =
    +      createProcess_ "spawnCommand" (shell cmd){ close_fds = True } $> ()
    
     --------------------------------------------------------------------------------
     -- $kenv

With this is place the command

    (defalias
      rst (cmd-button "pkill kmonad ; sleep 0.2s ; kmonad ~/.keyboard_layout/x220-slot-ansi-us-colemak-dh-z.kbd"))

works for me.

@rosshadden can you confirm that this works for you as well?

**Comment by rosshadden** [comment]
I probably should have mentioned I had tried an `&&` first :sweat_smile: but @slotThe found and described the actual problem better than I could have.

**Comment by david-janssen** [comment]
Great :-). I'll take @slotThe suggestion and patch it into master when I can. When I do so, I'll close this issue.

**Comment by rosshadden** [comment]
For now I'm simply running kmonad in a `while true` loop, so simply running `pkill kmonad` makes it rerun with the same arguments.

**Comment by david-janssen** [comment]
Haha, that's a great hack, well done :)

**Comment by manna-harbour** [comment]
Another work around would be to close the extra file descriptors in the shell script.

**Comment by manna-harbour** [comment]
The patch included above is a good idea in general, but it might also be nice to have a built-in function to reload the config file, for when the config file is specified as an argument (#90).

**Comment by slotThe** [comment]
This should be fixed as of #131

@rosshadden can you confirm?

**Comment by slotThe** [comment]
I'll close this fow now, @rosshadden if you're still having issues feel free to re-open.

**Comment by rosshadden** [comment]
The change worked, thank you very much. Sorry for not responding sooner.
