### ISSUE TITLE
Missing documentation since recent version update

### ISSUE THREAD

**Issue by thoelze1** [david-janssen/kmonad#94]
We discovered missing documentation in #86. I'm just making this new issue so that whatever went missing doesn't get lost in the shuffle. Thanks!

**Comment by thoelze1** [comment]
Missing: why root privilege is necessary on Mac

https://github.com/thoelze1/kmonad/blob/refactor/doc/syntax_guide.md

**Comment by thoelze1** [comment]
Missing: using `list-keyboards` to determine "product string" for config on Mac

https://github.com/thoelze1/kmonad/blob/refactor/doc/configuration.md

**Comment by thoelze1** [comment]
I see that there are plenty of areas in kmonad that could use your attention. Since this issue is one that I can handle, I'd be happy to take care of it. I'll plan to submit a PR soon (unless you've already started)

**Comment by david-janssen** [comment]
I haven't started, and any help would be greatly appreciated.
