### ISSUE TITLE
macbook internal keyboard tap-next nothing sent for tap

### ISSUE THREAD

**Issue by focusaurus** [david-janssen/kmonad#98]
macos 10.15.6

I'm trying to capture logs of a single tap of "a" so I'm starting kmonad after a shell sleep so when it starts I have TextEdit up so the first thing kmonad sees should be the tap of "a".

The next part (acting like shift) is working, but the tap never seems to fire.

[tap-next.txt](https://github.com/david-janssen/kmonad/files/5280039/tap-next.txt)

**Comment by thoelze1** [comment]
My understanding is that you built off of 99f9a05 after applying the unmerged bug fix in #95, is that correct? 99f9a05 fixed a bug that could be responsible for the behavior I see in your output, so if you built off of an earlier commit you could retry from 99f9a05.

**Comment by focusaurus** [comment]
I compiled `develop` at a2f232137cf8ff671c09a5a32d982d253d08ae53 plus hacking in the fix from #95. I don't want to waste folks' time though so I'll probably wait until PRs land and we think `develop` is good to go on mac.

**Comment by thoelze1** [comment]
Got it. FYI, the branches have changed around in the past few weeks. I've been making PR's on `master`, which has more recent activity than `develop`, but maybe that should change now that `develop` exists. I'll raise an issue about this.

Also, @david-janssen doesn't use macOS so I'm the primary maintainer of the macOS interface for kmonad - I think `master` (after the fix from #95) is good to go (but of course feel free to wait for the PRs to land). Honestly I'm super happy that other macOS users are testing out kmonad on different hardware than I have! So thanks!

**Comment by focusaurus** [comment]
OK I recompiled on master at 99f9a05eb1707940b933ed9a838242833248d30e plus the 1-liner from #95 but I am still unable to get a 1-char defsrc to work:

```
(defcfg
  input (iokit-name "Apple Internal Keyboard / Trackpad")
  output (kext)
  fallthrough true
  allow-cmd false
)

(defsrc a)

(deflayer test1 z)
;;(defalias a-S (tap-next a lsft))
;;(deflayer base @a-S)
```

```
Opening KeySink
Initializing Mac key sink
Opening KeySource
Opening IOKit devices
Launching process: emitter_proc
IOHIDDeviceOpen error: e00002e2
```

**Comment by thoelze1** [comment]
Are you running with `sudo`? See #86

**Comment by focusaurus** [comment]
Yes, I'm running with sudo and I tried the virtual_keyboard_example thing and it seems to work.

**Comment by thoelze1** [comment]
Do you have `Terminal` enabled in `System Preferences` > `Security & Privacy` > `Privacy` > `Input Monitoring`?

**Comment by focusaurus** [comment]
I did not initially have Terminal.app in Input Monitoring. I'm running kmonad in ITerm2 and my typing tests in either iTerm2 or TextEdit. So when I added iTerm2.app to Input Monitoring, restarted iTerm2, and restarted kmonad from within iTerm2, it looks to be working!

**Comment by focusaurus** [comment]
OK I made a larger `defsrc` and things are definitely working now. I will send a PR with some doc updates but I think so far:

- (temporary issue) need master plus #95 
- need to compile with the `--extra-include-dirs` which is now documented
- Need to allow Input Monitoring in whatever application launches kmonad. iTerm2 in my case. Curious how this will work to launch kmonad from launchd or something more permanent

**Comment by thoelze1** [comment]
@focusaurus I am interested to hear how things go if/when you try launchd
