### ISSUE TITLE
Clarify branches/contributing

### ISSUE THREAD

**Issue by thoelze1** [david-janssen/kmonad#99]
Now that there's a `develop` branch, should contributors make PRs on `develop` rather than `master`? Maybe it would be worth adding a couple of sentences about branches/contributing in the docs somewhere? Or maybe not :) Thanks as always!

**Comment by david-janssen** [comment]
That's a very good idea, and something that I might be able to do when I can't focus particularly well. Thanks for the good idea. Expect some progress here in a day or two.
